### ISSUE TITLE
Card with href tag is not generating an anchor object in the final page

### ISSUE THREAD

**Issue by LukeHagar** [Brain-Bones/skeleton#126]
Card with href tag is not generating an anchor object in the final page
![image](https://user-images.githubusercontent.com/98849695/185696190-c328404a-0b77-46c5-a1fb-cb3ab606cfdf.png)
![image](https://user-images.githubusercontent.com/98849695/185696298-f8aedc07-b39c-4b4a-9cc7-8d198f1ced13.png)
![image](https://user-images.githubusercontent.com/98849695/185696587-93b650bc-f721-4322-afa7-e10a06e99b36.png)

An example for the href value passed is provided in the last screenshot

**Comment by LukeHagar** [comment]
I'm an idiot, and thinking that the nature of buttons taking on anchor tags applied to cards as well.

Feel free to close this or mark it a feature request

**Comment by endigo9740** [comment]
I was about to say that's not a valid properly for a Card (which uses a div as the parent). No worries man. Just FYI you can hit the CLOSE button yourself directly under where you right replies.

I'll grab this one while I'm here though! Thanks!
