### ISSUE TITLE
Fix regression issue with Vitest tests

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#127]
See the screenshots below. Will need to research the issue, but most tests are failing.

![Screen Shot 2022-08-19 at 3 12 54 PM](https://user-images.githubusercontent.com/1509726/185699966-4c0dc424-561b-4374-965b-ae6d5233ef54.png)

![Screen Shot 2022-08-19 at 3 13 01 PM](https://user-images.githubusercontent.com/1509726/185699969-3e75d85a-b169-4f38-8aa9-d7e11b3996c9.png)

**Comment by LukeHagar** [comment]
I want to note as well since its the item that failed at the top, that TabGroup doesn't work with a manually specified class prop for me at all

**Comment by LukeHagar** [comment]
My input isnt even relevant, I'm operating on the Master

**Comment by endigo9740** [comment]
@LukeHagar No worries, but just FYI component issue you're describing would be a separate non-related issue. Feel free to migrate that to its own dedicated issue if you would like help troubleshooting. Note that I may ended purging our conversation from this thread to keep it on topic and tidy. Thanks!

**Comment by LukeHagar** [comment]
You already fixed it in dev vs master

**Comment by endigo9740** [comment]
@niktek Totally blaming you on this one btw (kidding, just kidding)

FYI It seems to be related to the alias setup for `import X from @brainandbones/skeleton`, or at least that's my best guess so far. I may not have time to finishing debugging btw EOD. But if you get a chance feel free to take a stab at it. You'll note I've created a branch for this if you have access:

`bugfix/vitest`

No worries if you need to create your own though.

**Comment by niktek** [comment]
So the issue is that the tests are copied into the package folder on ` pnpm package` and end up duplicating.  Root case is that we need to strip the tests from being sent to the package in the first place.  Nice up shot of a fix is that it will reduce the size of the package as well.
