### ISSUE TITLE
Minor design refresh for Alerts component

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#141]
The current design:

![Screen Shot 2022-08-22 at 2 21 09 PM](https://user-images.githubusercontent.com/1509726/186001768-e7a54129-942b-417c-8280-13ebb7c95fd3.png)

Proposed design:

![Screen Shot 2022-08-22 at 2 21 03 PM](https://user-images.githubusercontent.com/1509726/186001776-89bf479c-ff16-4630-b131-d96e909bf8eb.png)

**Comment by endigo9740** [comment]
Here's the results on the branch. PR submitted for review. Note the new default color using "accent", which seems more appropriate.

![Screen Shot 2022-08-22 at 2 52 42 PM](https://user-images.githubusercontent.com/1509726/186007043-16be28ee-d73b-4703-8d34-a4e89a735b9e.png)

![Screen Shot 2022-08-22 at 2 52 34 PM](https://user-images.githubusercontent.com/1509726/186007058-8fd3c14a-ca4a-4981-9e37-48ec3f635224.png)

**Comment by thomasbjespersen** [comment]
Typo needing fix in docs under the lead description in properties.
![Screen Shot 2022-08-23 at 1 18 03 PM](https://user-images.githubusercontent.com/52718757/186247438-2019d728-91fd-49af-bb55-733dd35cfa88.png)

**Comment by endigo9740** [comment]
This has been fixed on the branch. You can see this reflected on the pending PR as well.
