### ISSUE TITLE
Investigate support for Tailwind Alternatives (Windi, UnoCSS, etc)

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#152]
These include but are not limited to the following:

- [windi](https://windicss.org/)
- [unocss](https://uno.antfu.me/)

General idea is some folks choose to use these in favor of Tailwind. We've had a handful of questions or requests for support of these. So the first step is to review what can be done, document hurdles to overcome, then discuss adjustments that would allow for these to run.

See @niktek message regarding progression on Windi:
https://github.com/Brain-Bones/skeleton/discussions/79#discussioncomment-3461511

Known issues can be documented below:

- The Skeleton's [Tailwind-specific plugin](https://github.com/Brain-Bones/skeleton/blob/dev/src/lib/tailwind.cjs) would have to be replaced
- (will expand this as we investigate further)

**Comment by endigo9740** [comment]
I've been meaning to update this ticket, but I did do some research into supporting these alternative libraries. Unfortunately they are not plug and play replacements. 

- UnoCSS: this essentially allows you to create your -own- Tailwind-like utility system. But would not include any of the utility classes used within our components by default. Level of effort would be too high to support this right now.
- Windi - this is interesting because it's mirroring the utility classes from Tailwind. Unfortunately they still don't have feature parity with Tailwind v3. By the time Tailwind v4 rolls out they'll most likely be two versions behind. Worth keeping an eye on, but not in a state we could support this yet.

I'd be happy to chat with anyone that would want to take a means for supporting these or similar tools in the future though. Their interesting in concept for sure!

**Comment by sphinxc0re** [comment]
UnoCSS actually comes with a lot of presets including a Tailwind / Windi compact preset (https://github.com/unocss/unocss/tree/main/packages/preset-wind) that is compatible with Tailwind in a lot of ways. Especially with UnoCSS it's absolutely worth considering as the DX improvements are superp. It's the fastest utility css framework out there.

**Comment by Peyman-Borhani** [comment]
The way UnoCSS works is interesting, a better idea, the workflow, efficiency and DX are the advantages.
Flowbite, Daisy UI and others had UnoCSS presets, but skeleton was missing...
I was searching to find the best UI components kit, and after comparisons I found Skeleton to be a bit better than others.

**Comment by endigo9740** [comment]
I'd ask you guys to please avoid posting on closed issues. I'll get notified of them, but no one else.

We investigated Windi, but found it lacking in many ways. It's not a plug and play replacement for Tailwind. I was determined that it doesn't even provide parity with Tailwind v2, much less v3. We would end up limiting Skeleton to support it, and we would have many extra hoops to jump through.

Per Uno, again, not a plug and play replacement. It's a "build your own Tailwind" solution, which sounds fine on paper. But would again be very detrimental to our effort as we need something turnkey and ready to go. Tailwind provides this. Uno does not.

Furthermore, keep in mind that Skeleton is managed by a small team, with myself being the only full time contributor. We can't support every feature on a whim. Rather, if you wish to see a feature added, be the change you wish to see and submit a PR. Though with something of this scale I'd recommend joining Discord so we can discuss the details and plan ahead of time.

For now Windi is not a part of our roadmap and there's no plans to add it. Thanks for your interest though.
