### ISSUE TITLE
Drop store import from Accordion doc

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#153]
Writable store are no longer needed for the accordion, so the whole Typescript code block shown can be removed from the docs page:

![image](https://user-images.githubusercontent.com/1509726/186550947-d35b9bb6-0548-4c88-a48a-b21adf8ffd6d.png)

**Comment by 0xPranjl** [comment]
I have removed the two imports and opened a PR

**Comment by endigo9740** [comment]
Awesome, thank you sir!
