### ISSUE TITLE
Config.kit.package issues

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#156]
This is 100% a @sveltejs/package issue.  Setting up on a new laptop:

`pnpm i`
```
Running postinstall script, failed in 145ms
.../node_modules/@sveltejs/kit postinstall$ node svelte-kit.js sync
│ > config.kit.package has been removed — use @sveltejs/package instead
```

Removing the package key in `svelte.config.js` (which we used to prevent the tests from being packaged and conflicting with the testing commands) does make it work again.   However their documentation hasn't changed yet in terms of where we now add the config to exclude these files.  Doesn't seem to affect `npm`  installs afaics.

**Comment by endigo9740** [comment]
Glad you posted this, I keep meaning to bring it up, but I was still seeing tests in `/package` being picked up when I ran the tests recently. I opted to just nuke the package folder while working on the tests. So this is causing issues and is also not apparently solving the issue. I'll take to take a look soon!
