### ISSUE TITLE
Allow svelte:prefetch in Button

### ISSUE THREAD

**Issue by ak4zh** [Brain-Bones/skeleton#159]
Since Button allows href prop it should also allow `svelte:prefetch`

**Comment by endigo9740** [comment]
Hey @Ak4zh, Button is one of a handful of components in Skeleton that take advantage of Svelte's `$$restProps` feature.

You can see it used in the source here, just note we modify the value slightly to avoid conflicts with arbitrary class:
https://github.com/Brain-Bones/skeleton/blob/dev/src/lib/Button/Button.svelte

What this means is that we pass any arbitrary attributes assigned on the component definition to the component template itself. By default the Button uses a `<button>` but if an href attribute is applied it switches to an `<a>`. This is helpful if you want to say, add `type="submit"` to a button in a form. In theory `svelte:prefetch` should carry through in well. However, given it's a Svelte-specific attribute, I'm not sure how this interact with $$restProps.

Would you mind testing this and confirming if it works for you please? If not we can research and investigate level of effort to add this. Thanks!

**Comment by endigo9740** [comment]
Also note it's on our agenda to update the docs to better reflect which docs make use of `$$restProps`. Right now users have no way of knowing without looking at the source. We'll fix that soon!

**Comment by ak4zh** [comment]
`svelte:prefetch` does not work currently also passing it as a prop may not work.
I guess you need to do:

```
{#if prefetch}
<svelte:element
	this={tag}
	class="comp-button {classesButton} {$$props.class}"
	{href}
	data-testid="comp-button"
	on:click
	{...prunedRestProps()}
	{role}
	tabindex="0"
	aria-label={label}
	aria-describedby={describedby}
	aria-disabled={$$props.disabled}
        svelte:prefetch
>
	<!-- {...$$restProps} -->
	{#if $$slots.lead}<span><slot name="lead" /></span>{/if}
	<span><slot /></span>
	{#if $$slots.trail}<span><slot name="trail" /></span>{/if}
</svelte:element>
{:else}
<svelte:element
	this={tag}
	class="comp-button {classesButton} {$$props.class}"
	{href}
	data-testid="comp-button"
	on:click
	{...prunedRestProps()}
	{role}
	tabindex="0"
	aria-label={label}
	aria-describedby={describedby}
	aria-disabled={$$props.disabled}
>
	<!-- {...$$restProps} -->
	{#if $$slots.lead}<span><slot name="lead" /></span>{/if}
	<span><slot /></span>
	{#if $$slots.trail}<span><slot name="trail" /></span>{/if}
</svelte:element>
{/if}
```

**Comment by endigo9740** [comment]
Hmm, well that's a bummer. Unfortunately I don't think that's going to be the solution for this component. It add a lot of redundancy to the code (make it much less "dry") and could easily introduce regressions during maintenance. Plus it gets much worse when you take into account the other anchor-specific attributes like:

https://kit.svelte.dev/docs/a-options#sveltekit-reload
https://kit.svelte.dev/docs/a-options#sveltekit-noscroll

Perhaps instead, if prefetch is a hard requirement for you, to switch to native anchor element in your project and style it to match the Skeleton aesthetic. The Skeleton theme system is available throughout your project per the "Usage" section detailed here:

https://skeleton.brainandbonesllc.com/guides/themes

To replicate our "primary-filled" button style you would do the following. This would support themes and dark mode:

```css
.anchor-prefetch {
    @apply inline-flex justify-center items-center space-x-2 text-center whitespace-nowrap ring-inset text-base px-5 py-2.5 bg-primary-500 !text-white fill-white rounded-lg hover:brightness-110 transition-transform active:scale-95;
}
```

Then apply it to your anchor like this:

```html
<a href="/" class="anchor-prefetch" svelte:prefetch>Link</a>
```

That said, I still want to dig into this a bit more. If there's an elegant available then we'll implement it for sure! Unfortunately this just may be a combination of features the Svelte team hasn't had the foresight to consider. I may actually extend this over to their support team and see if they have other suggestions as well.

**Comment by endigo9740** [comment]
FYI if we can't find a good way to bundle this feature into the component, I'll look to bundle and distribute these CSS styles into the package. That way folks don't have to replicate these over and over on their own. I have an idea how to do that with a new update coming in the next release though!

**Comment by endigo9740** [comment]
@ak4zh I had posted another message here, but please disregard. I've tested this a bit further on my own and here's what I've found.

NOTE it is `sveltekit:prefetch` not `svelte:prefetch`, so make sure you apply this correctly:
https://kit.svelte.dev/docs/a-options#sveltekit-prefetch

I've tested the following

```
<a href="/docs/why" sveltekit:prefetch>Test</a>

<Button href="/docs/why" variant="ghost" sveltekit:prefetch>Test</Button>
```

The result rendered in the DOM:
![Screen Shot 2022-08-27 at 2 43 09 PM](https://user-images.githubusercontent.com/1509726/187045680-a5487b9d-9d9d-430f-8909-06b2cc6c5092.png)

Per the end of end of the component-generated anchor tag you can see `svelte:prefetch="true"`, so so the attribute is being applied, though ill formatted. However, you're correct it doesn't seem to functionally work:

- When I hover the anchor, I see a network call in Chrome to fetch the desired preload page
- When I hover the Skeleton Button, I do not see this same network call occur

So yeah, unfortunately it looks like this does not work even though the attribute is carried across. I do want to point out this issue open issue I found, which Rich Harris has added to the v1.0 milestones:
https://github.com/sveltejs/kit/issues/790

It may be a possible solution for this problem long term. However, in the meantime it doesn't seem prefetch will work with components. Your proposed solution will not work when you take into account all three of the anchor-only attributes. It would be a mess!

Your best best will probably be to forego Skeleton Buttons for anchors in favor of native anchor tags with prefetch added. I'd advise you setup a reusable class that adapts to the Skeleton theme. See "Usage" here to help with that:
https://skeleton.brainandbonesllc.com/guides/themes

If you need help replicating the Skeleton button styles let me know and I'll be glad to help.

**Comment by endigo9740** [comment]
And note I've copied this ticket to our Discord for other contributors to review. If we can find an elegant solution, we'll implement it for sure!

However, the issue appears to lie more in how Sveltekit prefetch and Svelte components operate. They don't seem to play well together. This might be an issue worth reporting to those teams specifically. Perhaps they could help troubleshoot the issue. I'll see if I can work up a barebones REPL showcasing the fault here.
