### ISSUE TITLE
Refactor the drawer component

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#167]
The Drawer component suffers from a number of issues:

- The documentation is a mess and doesn't properly detail how to implement or use this component
- We should probably designate it a Utility, as it's not really a standard component
- It needs to be more turnkey to implement, perhaps paired with App Shell
- The width of the drawer should be customizable
- I was having trouble implementing the visibility toggle
- Should have an option to make it take fixed size or overlay on demand (not just responsively)

**Comment by endigo9740** [comment]
This will come as part of this update:
https://github.com/Brain-Bones/skeleton/issues/158

**Comment by endigo9740** [comment]
Great progress on the Drawer today.

- I've decoupled the AppShell left sidebar from the Drawer component.
- Both AppShell/Drawer now use a 'shared' component for the Docs site
- The result is MUCH cleaner, less trying to cram everything into one component
- I've the theme to better match Dialog backdrop styling
- It's now using Svelte's built in Transition methods (backdrop fades, drawer slides in)
- Drawer component is now simpler (one slot), but comes with 4 positions (left/right/top/bottom; shown below)
- Note only the left animation is working as expected so far, but I'll fix that.

![Screen Shot 2022-08-30 at 9 34 15 PM](https://user-images.githubusercontent.com/1509726/187579975-10d81485-6294-4fe2-b16c-d6797105e30f.png)

**Comment by endigo9740** [comment]
Progress on the new Drawer component:
https://i.imgur.com/pyLQICQ.mp4

It now supports animation from any of the four positions. Works really well in execution!

**Comment by endigo9740** [comment]
Vitest integration cases have been added. I think with this the component is ready for QA!

Please pull branch `feat/app-shell` to begin testing asap @thomasbjespersen @niktek

**Comment by endigo9740** [comment]
When testing the Drawer component within the Skeleton docs project, the Svelte transition animations work as expected. The drawer shim fades in, and the drawer itself slides in from its respective position side.

https://i.imgur.com/8bviYW3.mp4

However, when bundled into a tarball (.tgz) package and installed in a test SvelteKit project, only the fade animation is functional. The fly/slide animation is not present:

https://i.imgur.com/FaPPG65.gif

We'll need to troubleshoot where and how this is failing. My guess is it's not picking u the window size uses for the x/y transition settings.

**Comment by endigo9740** [comment]
@niktek @LukeHagar

I'm at a bit of a loss on this issue. The Svelte fly transition works as expected when running the local dev server via `npm run dev` of the Skeleton project. It also works fine when you build `npm run build` and then preview with `npm run preview`. However, when I package it up and install the package in my standalone test app, the fly animation breaks every time. So far I've tried:

* Running as is, per above
* Running with a different means of capturing the window width data
* Running with hardcoded values for the fly transition x/y values in the template
* Making the backdrop/drawer elements siblings rather than parent/child

Nothing seems to work. The fade animation always works on the backdrop, but the fly animation never does. Perhaps we've run into some kind of bug?

I'd welcome your help in testing this. This only thing I can think to do at this point is drop the Svelte transition and animate it directly. Though this will come with a much more significant overhead since there's animations in/out for four separate positions.

**Comment by endigo9740** [comment]
Ok it gets a bit weirder still. If I drop the backdrop completely, make the drawer the root element in the component, then the fly animation works as expected! I'd been keen to use this, but it means the background area stays full opacity and you cannot click "off" the drawer to close it:

![skeleton-drawer-no-backdrop](https://user-images.githubusercontent.com/1509726/188711833-0fd17e35-ec85-4c76-8aed-a8f88a1de1b9.gif)

I thought perhaps having two animations within the same series of elements might be the the issue. So I attempted to make the drawer/backdrops siblings (both at the component template root). However, still no luck here. The backdrop fade seems to work, but the drawer fly fails. The drawer just pops into place:

![skeleton-drawer-siblings](https://user-images.githubusercontent.com/1509726/188711675-97deb7f1-2a44-407d-a3d5-51b9308278d4.gif)

**Comment by niktek** [comment]
Interestingly it works fine in Safari, but not Chrome/FF

**Comment by endigo9740** [comment]
That's why cross-browser testing is important Svelte team! Heh

**Comment by endigo9740** [comment]
Released as part of v0.37.32!
