### ISSUE TITLE
New Component: App Bar

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#168]
As part of the App Shell and Drawer updates, let's go ahead and introduce an app bar (aka "top" bar)

Example:
https://mui.com/material-ui/react-app-bar/

This will come as part of this update:
https://github.com/Brain-Bones/skeleton/issues/158

**Comment by endigo9740** [comment]
Documentation added. Also adjusted the default styles a bit to contrast with the background.

@niktek Feedback is welcome here!

![image](https://user-images.githubusercontent.com/1509726/187753050-d863685e-0196-4639-8c22-e1ba33216b8c.png)

**Comment by LukeHagar** [comment]
I really love this and the app shell, and I will be using them soon

**Comment by endigo9740** [comment]
Tested this in standalone SvelteKit project, and worked as expected. See my results here:
https://github.com/Brain-Bones/skeleton/issues/158#issuecomment-1237440196

**Comment by endigo9740** [comment]
Released as part of v0.37.32!
