### ISSUE TITLE
Data Table text color cannot be customized

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#175]
Currently the Data Table component is hardcoded to the following text colors:

```
text-surface-900 dark:text-white
```

However, this should be updated to adapt to the global text style colors. Additionally, we should allow these colors to customized with custom props.

**Comment by endigo9740** [comment]
I've removed the hardcoded color values, allowing the text to default to the inherit text styles of the page. However, I've also introduced a new `color` prop that allows you to define the text colors for each individual table.

![Screen Shot 2022-09-01 at 3 23 42 PM](https://user-images.githubusercontent.com/1509726/188005363-f5f7bf50-d3c1-4881-9cfb-c4015b9941c8.png)

**Comment by LukeHagar** [comment]
Fix validated
