### ISSUE TITLE
Avatars resizing on load and refresh

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#184]
![Kapture 2022-09-06 at 11 23 14](https://user-images.githubusercontent.com/52020637/188527916-6e8dc9c4-e97b-433d-bc19-d8055018edd2.gif)

Happens on initial page load and refresh in Safari/Chrome/FF

**Comment by endigo9740** [comment]
I've seen this as well and it's more noticeable now that we're using avatars on the homepage. I'll look to improve this before release this week!
