### ISSUE TITLE
Improve Component Consistency

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#194]
We've created and implemented a lot of new design patterns and paradigms over the last few months. I think it would be useful to go through and ensure all components are in sync with the latest standards.

**NOTE: THIS UPDATE WILL INTRODUCE BREAKING CHANGES**

## Code Consistency

- [x] Ensure we're following similar conventions for component prop naming
    - [x] All instances of `borderSize` changed to `borderWidth` to match Tailwind/CSS
    - [x] All instances of `ringSize` changed to `ringWidth` to match Tailwind
- [x] Ensure we define our component scripts in a consistent manner
- [x] Some of our earliest components many be due for a refactor and cleanup
- [x] Remove or reduce the use of `variants`, we should favor Tailwind class props
- [x] Ensure all use of `$$props.class` has a fallback of `''` to remove `undefined` appearing in DOM
- [x] Ensure consistence application of "id" classes for each element within the component templates. 

## Component Docs

- [x] Add and improve interactive examples
- [x] Improve usage instructions and code snippets
- [x] Ensure all available component props are documented and accurate (type, description, etc)
- [x] Ensure all components that utilize `$$restProps` have this documented clearly

## Design Consistency

- [x] Verify that we're using a cohesive visual style and aesthetic.
- [x] Hover state styles should be standardized

## Introduce Tailwind Elements

We've opted to deprecate several components in favor of static Tailwind CSS styled elements.
 
- https://github.com/Brain-Bones/skeleton/issues/240
- https://github.com/Brain-Bones/skeleton/issues/216

**Comment by endigo9740** [comment]
@niktek @LukeHagar @thomasbjespersen (and anyone else) I welcome additional discussion or suggestions here!

**Comment by endigo9740** [comment]
(reserving this space to note what has updated)

**Comment by endigo9740** [comment]
(reserved - I'm going to self-report some issues here)

**Comment by endigo9740** [comment]
This is ready to test! Everyone is welcome to pull down the PR and test locally. Please submit your feedback here. Thanks!

**Comment by endigo9740** [comment]
Note I've completed a round of updates. The first was just general QA and cleanup fixes. The second added more "selector classes", the id-like classes we use to describe each element within the component templates.

**Comment by endigo9740** [comment]
Merged this into dev, but reopening this ticket so QA can continue forward over the next week.

**Comment by salisshuaibu11** [comment]
1. The fill property on the button component is not taking effect.
2. If you check the list component under selection ListBox there is a writing typo in the description the "to" that comes before the store needs to get removed.
3. missing toggles for rounded and cursor props in the Avatar component, I think it will make sense if you add those.
4. There is a need to add an interactive example for the Badges component the way you did it for the Avatar, check mantine's badges.
5. How about code that we are adding as a usage to be referring to the component examples, what's your opinion on this? The reason am bringing this up is because the doc for BreadCrumb is unclear to me, but I don't know for others.

@endigo9740 you can start with these ones for now before I am done with the testing

**Comment by endigo9740** [comment]
@salisshuaibu11  The button component wasn't touched in this update. It's been pulled to it's own dedicated ticket. But I noted your posted on there already.

We're adding interactive examples over time as I'm still settled on the best way to handle a few things. We'll have them for most components eventually. Though some like Cards work a bit better as is.

Let's chat about the Breacrumb a bit more tomorrow. I'd like to hear your thoughts.

Thanks though, this is a great start!

**Comment by niktek** [comment]
Safari (of course) doesn't show the initials on components/avatars even though the rendered HTML has it and it shows fine in other browsers like Chrome.

**Comment by niktek** [comment]
Safari..... http://localhost:5173/components/range-sliders Accent doesn't work.  Works fine in other browsers.

**Comment by endigo9740** [comment]
Yeah, I'm aware. Hopefully they resolve that soon!

**Comment by endigo9740** [comment]
@salisshuaibu11 @niktek The items you mentioned above have been fixed and changes push to `dev` branch. Please confirm.

@salisshuaibu11 I didn't include the Avatar `cursor` in the preview because it's not very visibly notable. Also we never followed up on your issue with the breadcrumbs. If you can provide more details on what's unclear there I'd be happy to explain. Breadcrumbs are a component that have been part of web pages since early days. I'm not sure what else we can do to explain them. But I'l open to ideas!

**Comment by salisshuaibu11** [comment]
Is okay, is clear now.

**Comment by endigo9740** [comment]
I've created a new ticket to track the progress on these updates for the items not completed in this upcoming release:
-https://github.com/Brain-Bones/skeleton/issues/254

**Comment by endigo9740** [comment]
Part 1 is released. Part 2 coming up soon!
