### ISSUE TITLE
Refactor and improve the Dialog utility

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#197]
Updating these instructions to detail the current list of requirements and desired updates:

- [x] Better transitions when moving between queued dialogs
- [x] Should allow for custom/interchangeable svelte components as the modal contents
- [x] Consider implementing a universal "focus trap" action for code reuse, include as part of the library
- [x] Should remove hardcoded English words, for basic i18n support (ex: "Confirm" for button)
- [x] Should be updated to the standards of all current components, per the consistency and Sveld updates

*EDIT*

We've opted to pass on using the native dialog element. It has too many quirks to work around right now:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by motopods** [comment]
<dialog> requires Safari at least greater than or equal to 15.4，is this requirement a little too strict?

**Comment by endigo9740** [comment]
Hey Motopods, first off there's no guarantee we'll move forward with this. As noted, we're just going to investigate the technical capabilities. There's plenty of issues that could prevent us from moving forward. But the reason I'm keen to add it is due to the a11y benefits, such as proper focus capture. Things that are very difficult with custom rolled solutions.

The Dialog elements was adding in Safari in 15.4, which came out six months ago:
https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/

Version 16 is now the current version:
https://webkit.org/blog/13152/webkit-features-in-safari-16-0/

So 15.4 is a version behind. If this was IE, where corporate users were limited from being able to update, I might be more concerned. However, Mac is primarily a consumer OS. Users do not face the same barrier for updating.

A11y is important and Chrome has had this since 2014, so honestly it's frustrating it's taken this look to be available cross-browser. Safari has long been a hold out on very crucial features.

The main thing to keep in mind is Skeleton is a pre-release/beta software. It's not intended for production use YET. That's what v1.0 will signify. By the time it is I think this feature would have had plenty of ramp up time for anyone that is going to update, to have updated.

**Comment by endigo9740** [comment]
Feature request to prevent dialog from closing until prompt is completed:
https://github.com/Brain-Bones/skeleton/issues/385

**Comment by endigo9740** [comment]
Feature request: be able to replace the entire contents of a dialog via component templates

**Comment by endigo9740** [comment]
Feature request: custom "confirm" button text.

**Comment by endigo9740** [comment]
Note, all above and current feature requests have been included in the original post at the top of this thread.

**Comment by endigo9740** [comment]
![Screen Shot 2022-11-01 at 5 04 37 PM](https://user-images.githubusercontent.com/1509726/199352157-09a1cfd2-1ba6-477d-b555-2c4e7e940ffb.png)

Made some progress today, but documenting a few outstanding issues I need to work though with the native `<dialog>` element:

1. Our previous Dialogs handled display via a "if" statement, but we should probably lean into the native `open` attribute or trigger `showModal/show/close()` methods
2. Svelte transition animations may only be possible with the "if" statement method
3. Tailwind doesn't handle the `::backdrop` element styling well. `backdrop:bg-black/50` works, but `backdrop:bg-surface-500/50` does not.
4. Currently I don't believe the native element will support a visual stacked queue. We may need to opt for a "swap" effect.

I'll pick up on this tomorrow and update with my progress asap.

**Comment by endigo9740** [comment]
I've spent more time on this but continue to run into issues with the native element. I've copied my Discord message to save some time here:

![Screen Shot 2022-11-02 at 12 37 19 PM](https://user-images.githubusercontent.com/1509726/199561714-e6c2e489-8dd6-4e8e-90d6-c4854688d9b8.png)

**Comment by endigo9740** [comment]
Notable updates for today:

- Component examples for a ListBox and video embed added
- New Focus Trap action created. This is reusable, and will be part of the library
- Flushed out the docs for both Focus Trap and the Dialog utility
- Implemented a means to apply class styles per dialog instance via `classes`
- Began testing how to animate the transition between dialogs

Still some work to be done with the dialog transitions, but I'll pick up here tomorrow!

**Comment by endigo9740** [comment]
All notable features are now implemented so marking this ready for QA!
