### ISSUE TITLE
Refactor and improve the Toast utility

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#198]
The store queue we have now fully supports this, we're just not taking advantage of it currently. The idea is toast messages would stack in some fashion, like so. Though I'm open to other suggestions!

> NOTE: don't forget a11y when implementing this!

[![image](https://cdn.arstechnica.net/wp-content/uploads/2020/11/big-sur-1.gif)](https://cdn.arstechnica.net/wp-content/uploads/2020/11/big-sur-1.gif)

**Comment by salisshuaibu11** [comment]
Why do you prefer it this way instead of stacking them on top of each other, though the UI is cool, in the end, the toast is still going to disappear after some time. But I think we can utilize the two by allowing the user to opt for the one he wants to use.

In the case of notifications, we can use the store queue just like the way this reminder is functioning, but for things like deleting, creating something e.t.c we can use normal toast. what do you think about it?

**Comment by endigo9740** [comment]
I haven't settled on any particular UI or layout yet. I'll dive deeper into this once I get to this ticket, which should be later this week. Just wanted to show an example of what's possible.

> in the end, the toast is still going to disappear after some time

The length of time they display can be adjusted, and there's setting to persist until dismissed. So it is possible for them to queue up. We need to handle that display when this occurs, or multiple come in at once.

**Comment by salisshuaibu11** [comment]
i came across this in twitter:

https://twitter.com/blvdmitry/status/1569772945702010881?s=20&t=oYVk5qc9u7HD8b-2Q6X2UQ

**Comment by salisshuaibu11** [comment]
i came across this in twitter:

https://twitter.com/blvdmitry/status/1569772945702010881?s=20&t=oYVk5qc9u7HD8b-2Q6X2UQ

**Comment by endigo9740** [comment]
@salisshuaibu11 This is great! I like that a lot. It's more of what I had in mind for sure.

**Comment by endigo9740** [comment]
I've made a bit of progress on this. It now allows for multiple to show vertically stacked, and also allows for custom background color per toast.

![toast-queue](https://user-images.githubusercontent.com/1509726/190828276-caac961e-192c-4e03-a73b-9219d7d614ae.gif)

Still working on some timeout bugs and the 3D stacked effected. But will return to this later!

**Comment by salisshuaibu11** [comment]
Nice work

**Comment by endigo9740** [comment]
Reference for myself: https://twitter.com/chriscoyier/status/1584564243814551552

**Comment by kimjunsung04** [comment]
Feature request: custom button text.

**Comment by endigo9740** [comment]
A draft PR has been started if anyone wishes to test this out:
- https://github.com/Brain-Bones/skeleton/pull/510

This includes a number of improvements:

- Allow for any corner or t/l/b/r position
- Enter/leave animations are based on the position
- Supports display of multiple toasts at once
- However, there's a max number possible (configured via the `max` prop
- Has more and better style adjustments

Still more to do, but here's some previews.

![Screen Shot 2022-11-04 at 5 02 42 PM](https://user-images.githubusercontent.com/1509726/200082041-061fb578-b087-4a92-94aa-942d7a8d7963.png)

![toasts-all](https://user-images.githubusercontent.com/1509726/200082043-cbedcf72-c8e4-460e-ae82-caf0d2b4c54a.gif)

![toast-br](https://user-images.githubusercontent.com/1509726/200082048-c2eeba8d-a8bf-4e18-abcd-438195e7bbb1.gif)

**Comment by endigo9740** [comment]
I've also pushed a handful of updates to the Toasts PR:

- Added support for HTML within message and action labels
- I've rebuilt portions of the Toast store to better support autohide (this was broken with multiple shown)
- Renamed the `ToastSettings` type and moved it to it's own `types.ts` file to follow convention
- Updated all portions of the Doc where toasts are used, including updating `index.ts`
- Added support for `classes` to customize one-off toast messages via the data object
- I've wrote the Usage instructions, follow the simpler structure used for Dialogs
- Updated the tests to get back in a working state

A couple notes of what's not present:

1. We do not have a means to animate a particular toast on dismiss. out:transition works, but not as expected due to the fact that the queue isn't a normal array, but a store value that happens to be an array. Svelte is looking for an update to the individual array item, but when the store updates it replaces the ENTIRE array, which throws off the animation. I'd welcome suggestions to work around this.
2. Ideally the toast should default to tertiary rather than accent color, but this doesn't work well due to the test color issues we're aware of with buttons, etc. When we introduce the on-{x} token styles for text color I'll look to change this.
