### ISSUE TITLE
New Component: KBD (keyboard)

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#200]
See a reference here:
https://mantine.dev/core/kbd/

Honestly I wouldn't mind a straight 1:1 port of the Mantine version here. The plan is to use these on the component documentation pages to highlight available keyboard shortcuts (ex: ESC to close a Drawer)

I'd recommend referencing how the Skeleton [Badge component](https://github.com/Brain-Bones/skeleton/blob/dev/src/lib/Badge/Badge.svelte) was built, this component should have a similar structure. It's purely presentational, not interactive. The main difference is this will really only one have slot, which provides the desired keyboard key or combinations (ex: ESC, SHIFT + 1)

> NOTE: it might help folks out if we link to a resource for finding unicode characters, such as: `⌘` (command on Macs)

Here's a diagram for how I suggest we lay this out:

![Screen Shot 2022-09-07 at 2 03 08 PM](https://user-images.githubusercontent.com/1509726/188957199-0fae557c-3fc9-4191-8028-5058ef5ff557.png)

Doing this will produce that raised/3D visual effect.

Make sure you follow the contribution guidelines when creating any new component!
https://skeleton.brainandbonesllc.com/docs/contributions

**Comment by LukeHagar** [comment]
@endigo9740 I would love to take a stab at this!

Ill examine the mantine example when I get a chance and mock something up.

**Comment by endigo9740** [comment]
Boom, assigned! Thank you sir!

**Comment by endigo9740** [comment]
On second though on this one, it may be possible to make the faux 3D effect just applying a thicker button border and rounding the element. Probably worth a try @LukeHagar

**Comment by LukeHagar** [comment]
Good point, they should stand out alot

**Comment by endigo9740** [comment]
FYI Luke has other other stuff come up so this component is available to anyone who wishes to take it on! Please let me know and I'll reassign it asap. Thanks!

**Comment by salisshuaibu11** [comment]
I will take this issue

**Comment by endigo9740** [comment]
@salisshuaibu11 Here's the final CSS we worked up:

```css
/* --- KBD (Keyboard) --- */

kbd {
	@apply font-bold text-sm bg-surface-300 dark:bg-surface-700 border-[2px] border-surface-500 rounded px-1 py-0.5;
}
```

Just drop the component, add this to the bottom of the `typography.css` file, then submit that as a PR. I'll accept it asap!

Thanks again for working with me and Nik on this! Always nice when we can collab as a group!
