### ISSUE TITLE
New Component: File Button

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#201]
References:
https://mantine.dev/core/file-button/

Similar to the plans for the [Copy to Clipboard action](https://github.com/Brain-Bones/skeleton/issues/199), I believe the File Picker might be better served as a Svelte Action instead of a dedicated component.

This one probably needs a bit of research, so feel free to review with me and other contributors (here or in Discord)

Please follow our contribution guidelines when implementing any new component!
https://skeleton.brainandbonesllc.com/docs/contributions

**Comment by endigo9740** [comment]
Added per @niktek suggestion

**Comment by endigo9740** [comment]
Note I'm 100% ok with us splitting the Dropzone to a separate dedicated ticket.

**Comment by salisshuaibu11** [comment]
I think is better if the dropzone would be a separate ticket

**Comment by salisshuaibu11** [comment]
@endigo9740 i want to take this

**Comment by endigo9740** [comment]
Thanks Salisu, I've assigned this to you. I'll go ahead and split the Dropzone off to it's own ticket.

**Comment by salisshuaibu11** [comment]
Alright

**Comment by endigo9740** [comment]
@salisshuaibu11 [Per our discussion on Discord](https://discord.com/channels/1003691521280856084/1022922385185312778), here's a summary of what's needed for this component:

- We will need to opt for a component, not action. So I'll rename this ticket.
- I'll provide an example of the Component and template markup examples below.
- General idea is it's a button + input:file. The input is hidden. When clicking the button it clicks the input.
- We can use `$$props.class` to provide arbitrary classes to the button, since it's the only visible UI
- We can use `$$props.value` to pass the binded input value up to any relevant forms this is used in
- We'll use a Slot to allow users to define their own button label text and icons.
- We'll pass the input `on:change` event up by setting this as an attribute

Here's and example of the Component, including the recommended name:

```html
<FileButton bind:value={someValue} class="btn-ghost">Upload File</FileButton>
```

Here's an example of the component definition, including the click handler:

```html
<script lang="ts">
	let elemFileInput: HTMLElement;
    function onButtonClick(): void {
        elemFileInput.click();
    }
</script>

<div class="file-picker">
    <input bind:this={elemFileInput} type="file" value={$$props.value} class="hidden" on:change>
    <button on:click={onButtonClick} class="btn {$$props.class}"><slot /></button>
</div>
```

As for props, these will all be applied to the input element:

- `name: string | undefined` - just the input name attribute
- `accept: string | undefined` - limits the accept file formats the picker can select
- `multiple: boolean` - toggles on selecting multiple files

Let me know if I can answer any other questions on this!

**Comment by salisshuaibu11** [comment]
@endigo9740 alright, thank you, I will jump on it. If there is anything I will let you know

**Comment by endigo9740** [comment]
Completed and merged!
