### ISSUE TITLE
New Component: Skeleton (placeholders)

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#205]
Reference:
https://bootstrap-vue.org/docs/components/skeleton

I'm a fan of how Bootstrap and other libraries handle this. Just a simple shape component with a subtle glowing animation.

> NOTE: I am concerned about the name conflict with the project. Perhaps we opt for `<SkeletonPlaceholder>` or just simply `<Placeholder>`?

![Screen Shot 2022-09-07 at 2 41 22 PM](https://user-images.githubusercontent.com/1509726/188963169-59c9b1d8-24fc-4e2e-9cd6-03bb7f391d52.png)

Let's start with at least these basic shapes, though text/button/input are a bit redundant (just different size boxes)

![Screen Shot 2022-09-07 at 2 41 29 PM](https://user-images.githubusercontent.com/1509726/188963172-7b3db757-30a3-4782-a70e-b43b7fa08c3b.png)

Please follow our contribution guidelines when implementing a new component like this!
https://skeleton.brainandbonesllc.com/docs/contributions

**Comment by salisshuaibu11** [comment]
Will work on the Skeleton

**Comment by endigo9740** [comment]
This is complete and merged, so closing the issue. Thanks again @salisshuaibu11!

**Comment by salisshuaibu11** [comment]
My pleasure
