### ISSUE TITLE
New Component: Timer

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#206]
Here's a few examples of the visual UI. It needs to keep the minimalistic/flat design aesthetic of Skeleton, but personally I really like the "flip" panels like you might see at an airport or train station. Would be cool if we can combine those two ideas, but this is not a hard requirement.

![](https://cdn.dribbble.com/users/5725311/screenshots/14483761/media/cf6a686783514828b44ec2a80afb4cc5.jpg?compress=1&resize=1600x1200&vertical=top)

![](https://cdn.dribbble.com/users/372375/screenshots/14483923/timepicker_still_2x.gif?compress=1&resize=400x300&vertical=top)

![](https://image.shutterstock.com/image-vector/flip-countdown-clock-counter-timer-260nw-1045553587.jpg)

[See more examples here...](https://www.google.com/search?q=material+design+timer&hl=en&authuser=0&tbm=isch&sxsrf=ALiCzsb9RyrN-wie0YBxd029zqz1tTeFFw%3A1662580023946&source=hp&biw=1707&bih=1233&ei=N_UYY5_wM5HekPIPg72I4Ac&iflsig=AJiK0e8AAAAAYxkDR9Fwlgb-jq9hw5luKt25WE8v0lDm&ved=0ahUKEwjf5-2duYP6AhURL0QIHYMeAnwQ4dUDCAc&uact=5&oq=material+design+timer&gs_lcp=CgNpbWcQAzIECAAQGDoECCMQJzoFCAAQgAQ6CAgAELEDEIMBOggIABCABBCxAzoLCAAQgAQQsQMQgwE6BAgAEAM6BggAEB4QCFAAWKkUYKMVaABwAHgAgAEziAGEB5IBAjIxmAEAoAEBqgELZ3dzLXdpei1pbWc&sclient=img#imgrc=R2RQQH8BowPKJM)

## Requirements:

- Should allow both counting down, as well as counting up
- Should support numeric values (ex: 1,000) and date/times
- We should avoid introducing third party libraries for this like Monument, etc. Keep it simple and self contained.
- It would be great to make use of Svelte transitions per each "tick" or change

Please review with me (here or on Discord) to discuss implementation details. I don't mind taking this one on myself!

Of course, follow our contribution guidelines when implementing any new components:
https://skeleton.brainandbonesllc.com/docs/contributions

**Comment by niktek** [comment]
I'll take this one!

**Comment by benzara-tahar** [comment]
@endigo9740  @niktek is this one unassigned? would like to give it a shot  this weekend if nobody is working on that

**Comment by niktek** [comment]
@benzara-tahar happy to let you have a go at it!

**Comment by endigo9740** [comment]
FYI after reviewing with @benzara-tahar we've decided to use his existing counter library found here:

- https://github.com/benzara-tahar/svelte-animated-counter
- Demo: https://svelte-animated-counter.vercel.app/

We'll create a new section on the Skeleton docs to house recommend tools like this one. I've also asked him to share any sort of sponsorship link has can provide so we can shout that out, along with his GitHub profile (similar to the Local Storage Store)

The location of this new "Recommendations" section is to be decided, but I'll be brainstorming this. May be something we can get in relatively quickly though.

**Comment by endigo9740** [comment]
New recommendations page added and including your library @benzara-tahar. Hopefully this works for you!

![Screen Shot 2022-10-19 at 10 44 05 AM](https://user-images.githubusercontent.com/1509726/196740390-90c33a62-dcdc-4910-935d-6684e5586f9b.png)
