### ISSUE TITLE
New Component/Feature Theme Switcher

### ISSUE THREAD

**Issue by luke-hagar-sp** [Brain-Bones/skeleton#208]
What do we think of dynamic theme switching?

Maybe something similar to the functionality of the lightswitch, perhaps you could dynamically import Theme CSS files?

Maybe a dropdown selector?

**Comment by endigo9740** [comment]
This has been proposed on the Roadmap already. See here:

![Screen Shot 2022-09-08 at 2 08 26 PM](https://user-images.githubusercontent.com/1509726/189205994-68c75c83-5e19-477e-95f9-ccf79116eec3.png)

The idea is I want users to be able to preview BOTH preset themes and custom created themes. But custom themes can be generated with both Tailwind colors and Hex colors. So essentially the CSS will have three sources. That adds some complexity here.

I have a rough idea of how I want to introduce this, but I believe this is out of scope for the upcoming release. The idea is good, we're going to implement it, but just yet. I believe level of effort will be fairly large, even if we introduce a third party tool to handle the theme swapping for us.

**Comment by endigo9740** [comment]
By the way, if you agree this can wait for now I might suggest we close the ticket. We can always reopen or recreate later!

**Comment by luke-hagar-sp** [comment]
Works for me!
