### ISSUE TITLE
Expose Lightswitch store?

### ISSUE THREAD

**Issue by jamesnewportbeach** [Brain-Bones/skeleton#218]
Can I somehow gain access to the Lightswitch store? I need to inform other components about that state when it changes and set it's state manually

**Comment by endigo9740** [comment]
Hey @jamesnewportbeach, this is not a use case we had accounted for, so we haven't made this super friendly to do this yet. However, it should be technically possible to do. I might recommend you review the component source here:

https://github.com/Brain-Bones/skeleton/blob/master/src/lib/LightSwitch/LightSwitch.svelte

You'll note we use `<script context="module">` at the top, which is what allows multiple instances of the component remain in sync. See the example on the Light Switch docs where both the documentation switch and the example on the page toggle in unison.

More relevant to your point though, you'll note we persist the user's preferred option to local storage, which you should be able to access:

```
localStorage.setItem('mode', $checked === true ? 'dark' : 'light');
```

The thing to note is we only set a value IF the user has opted to interact with the Light Switch component. A first time user that's never interacted with this will have no preferred option persisted, and instead we opt to use the operating system preference. You can get access to this via this part:

```
function setPreferredScheme(): void {
        const prefersDarkScheme: any = window.matchMedia('(prefers-color-scheme: dark)').matches;
        checked.set(prefersDarkScheme);
        // ...
}
```

This is checking for the setting of the `prefers-color-scheme` property from the browser. You can read more about this here:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

One final note - if whatever you're changing could be manipulated by CSS alone, then I'd highly advise you use the built-in Tailwind method for doing this:
https://tailwindcss.com/docs/dark-mode

This makes use of a special `dark:` modifier inserted directly before the CSS. So if you're wanting to only show a particular version of an element or component in light or dark mode, then you could do something like this:

```HTML
<!-- hidden by default in light mode, visible in dark mode -->
<div class="hidden dark:block">
```

Just flip the hidden/block values around if you want it the other way around.

**Comment by jamesnewportbeach** [comment]
I'm just not using localStorage to save where this setting is - i'm saving it in a database so when users change machines, their settings are retained - i'd love it if I could do that easily somehow without mucking with localStorage

**Comment by jamesnewportbeach** [comment]
Maybe if the value attribute is set on it, the component ignores localStorage and binds to the value, then it emits an on:change event upwards so we can set the value to whatever persistence layer we want...

**Comment by endigo9740** [comment]
I see, so you're trying to persist mode per an account (remotely) versus locally per device. We were certainly only targeting the latter in case preference differs device to device. Like, light mode might be better when you're outside on mobile, versus dark mode when you're inside at home.

In that cause this would require an extension to the Light Switch component to expose this information directly from the component. I'd suggest we either modify this ticket or create a new one that's a dedicated feature request for this. Likewise I'd accept a PR for this feature.

Outside of that, your best bet may be to learn from our component, but roll something custom that suites your project's unique requirements.

**Comment by endigo9740** [comment]
I've gone ahead and marked this a feature request. May not make it in the next update, but at least it's here and available!

**Comment by endigo9740** [comment]
This is a note for myself, but we should refactor the LightSwitch to take advantage of the new LocalStorageStore utility added here:

https://github.com/Brain-Bones/skeleton/issues/283

This doesn't directly help with exposing the value publicly, but the overall logic simpler.

**Comment by endigo9740** [comment]
@jamesnewportbeach Given there's a few updates pending for this component I've decided to create a new dedicated feature request ticket here. This will put a little more focus on what's being requested:

https://github.com/Brain-Bones/skeleton/issues/291

Please feel free to add any further feedback here please!

**Comment by endigo9740** [comment]
@jamesnewportbeach I couldn't copy you on the new ticket but @luke-hagar-sp made a great update to the LightSwitch for the next release. See his PR here, which we've merged:

https://github.com/Brain-Bones/skeleton/pull/293

In short, this takes the selection state from within the component, and moves it into Svelte Store. Not just any Svelte Store, but a new extended version we're introducing that includes local storage persistence.

The benefit is you have a couple ways to access this info:

- Check the local storage value, as you did before. But this isn't always quick and accessible
- Import the store itself to check the state. I just realized we didn't document this before the PR went in so I'll make sure to add that asap.

Please note this will still not given you the OS preference value, but you'll get three states from the store:

- `undefined` - user has not selected an app preference for light/dark
- `true` - dark mode
- `false` - light mode

If you get undefined from the store, check the OS settings via this:

`const prefersDarkScheme: any = window.matchMedia('(prefers-color-scheme: dark)').matches;`

- `false` - light mode
- `true` - dark mode

**Comment by endigo9740** [comment]
@jamesnewportbeach After speaking with @luke-hagar-sp he's going to look to build a second store value that houses the OS preference value. That way if you get `undefined` from the main store, you can then reference this as a fallback. The idea being that we need and want to maintain these values separately. But should be the finalize piece of the puzzle for informing your app what state it should be in.
