### ISSUE TITLE
Contribution guide updates

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#220]
A first time contributor may not know how to handle the process of submitting their first pull request (ex: fork, branch, update, push, PR). But I found two excellent resources that do a great job of walking you through the process...

This provides a lot of great high level details:
https://opensource.guide/how-to-contribute/

Likewise this provides step-by-step examples that guide folks through the process:
https://github.com/firstcontributions/first-contributions

We should aim to integrate some of this info int our Contributor guidelines. As well as briefly summarize the step-by-step instructions. I'm also fine with us linking to these links if it helps provide extra context.

I'd welcome help from anyone with the time and ability to do this!

### Side Note

The text copy for this page could use a proper review. There's a few typos, such as:

> Always pass the full Tailwind class name. Tailwind does not support ~contructed~ (constructed) class names

**Comment by lazyturd** [comment]
Hello. I'd like to be assigned to this

**Comment by endigo9740** [comment]
Awesome, thanks. This has been assigned to you!

**Comment by salisshuaibu11** [comment]
@lazyturd how is the contribution guide update coming up

**Comment by lazyturd** [comment]
> @lazyturd how is the contribution guide update coming up?

Hello, Good morning
I'm just slightly confused. Did you want me to create a contribution markdown file or just edit the one on the website and if it's the latter, how do I access the contribution page on the website

**Comment by endigo9740** [comment]
@lazyturd @salisshuaibu11 I'm already in-progress on a related issue so I'm just going to fold these changes into this ticket: https://github.com/Brain-Bones/skeleton/issues/237

If you have questions about contributing, then the contribution guide is meant to answer this. So hopefully with the revisions I made it'll make the process more clear! Very meta, but hopefully it helps :)

Thanks for your consideration all the same!
