### ISSUE TITLE
<App Bar> css background dark fails to load custom setting.

### ISSUE THREAD

**Issue by figuerom16** [Brain-Bones/skeleton#221]
Issue: In Dark Mode App Bar changes to lightest bg-surface-100 when changing dark:bg-surface-800 to dark:bg-surface-**900**.
Secondary: Tailwinds arbitrary value syntax doesn't work in App Bar dark:bg-#[000000]

Snippet in /src/routes/+layout.svelte:
`<AppBar background="bg-surface-100 dark:bg-surface-900">`

Steps to reproduce the issue:
1. Navigate to https://skeleton.brainandbonesllc.com/ then ensure page is in Dark Mode.
2. Ctrl + right click Skeleton header App Bar then inspect in the drop down menu.
3. Modify class of data-testid="app-bar" from dark:bg-surface-800 to dark:bg-surface-900
4. App Bar will turn white.

Thanks for making this project; I've been enjoying it profusely.

**Comment by endigo9740** [comment]
Hi @figuerom16, first off thanks for the kind words! We're glad to help!

Unfortunately I think you may be misunderstanding how Tailwind process classes with it's compiler. I'd be very leery of modifying Tailwind classes from the browser like that. Keep in mind that, when run, Tailwind's compiler is creating classes that match what's defined in your project files. By the time things hit the browser you no longer have a way to modify the classes like that and see live results.

What I'd recommend instead is import the AppBar in your own project, then define the background color as described in our documentation. I'm using some bright colors to make this affect obvious:

```
<AppBar background="bg-purple-500 dark:bg-green-500">...</AppBar>
```

Here's the results in using the Skeleton documentation site's app bar as a demo:

![Screen Shot 2022-09-13 at 1 19 26 PM](https://user-images.githubusercontent.com/1509726/189980097-6f46b73c-4359-4ad3-a220-4e4b20f1fbdd.png)

![Screen Shot 2022-09-13 at 1 19 12 PM](https://user-images.githubusercontent.com/1509726/189980103-e1240f95-0716-45f2-80d9-da09115e0d45.png)

The important bit to note is when you save your file, that triggers Tailwind compiler to process and add only the utility classes to the CSS bundled that's defined in your project files. It's a form of tree shaking if that makes sense. Only the classes implemented are included in the bundle. And only classes in the bundle can be used in the served version of the page.

Hopefully I've explained that clearly enough, but please do follow up if I can expand on anything.

**Comment by figuerom16** [comment]
I see I must have something misconfigured then in my project.
For some reason dark:bg-surface-700 and dark:bg-surface-800 works correctly, but fails for all other values of 100 (reverts to bg-surface-100).
<AppBar background="bg-surface-100 dark:bg-surface-900">

I'll double check the guide/documentation to see if I missed an important config and update if I figure out what I missed.

**Comment by endigo9740** [comment]
If the colors themselves are failing then perhaps check your theme? If you don't mind posting which presets your using here please, or if you generated your own please care the full generated CSS.

**Comment by figuerom16** [comment]
```
:root {
	/* --- Custom Tailwind Theme --- */
	/* primary (purple) */
	--color-primary-50: 250 245 255;
	--color-primary-100: 243 232 255;
	--color-primary-200: 233 213 255;
	--color-primary-300: 216 180 254;
	--color-primary-400: 192 132 252;
	--color-primary-500: 168 85 247;
	--color-primary-600: 147 51 234;
	--color-primary-700: 126 34 206;
	--color-primary-800: 107 33 168;
	--color-primary-900: 88 28 135;
	/* accent (teal) */
	--color-accent-50: 240 253 250;
	--color-accent-100: 204 251 241;
	--color-accent-200: 153 246 228;
	--color-accent-300: 94 234 212;
	--color-accent-400: 45 212 191;
	--color-accent-500: 20 184 166;
	--color-accent-600: 13 148 136;
	--color-accent-700: 15 118 110;
	--color-accent-800: 17 94 89;
	--color-accent-900: 19 78 74;
	/* warning (rose) */
	--color-warning-50: 255 241 242;
	--color-warning-100: 255 228 230;
	--color-warning-200: 254 205 211;
	--color-warning-300: 253 164 175;
	--color-warning-400: 251 113 133;
	--color-warning-500: 244 63 94;
	--color-warning-600: 225 29 72;
	--color-warning-700: 190 18 60;
	--color-warning-800: 159 18 57;
	--color-warning-900: 136 19 55;
	/* surface (gray) */
	--color-surface-50: 249 250 251;
	--color-surface-100: 243 244 246;
	--color-surface-200: 229 231 235;
	--color-surface-300: 209 213 219;
	--color-surface-400: 156 163 175;
	--color-surface-500: 107 114 128;
	--color-surface-600: 75 85 99;
	--color-surface-700: 55 65 81;
	--color-surface-800: 31 41 55;
	--color-surface-900: 0 0 0;
}
```

**Comment by endigo9740** [comment]
I've copy/pasted your exact background prop shown above and tested in both the Skeleton default theme, as well as the them you provided. Here's the results....

Skeleton theme:

![Screen Shot 2022-09-13 at 2 00 03 PM](https://user-images.githubusercontent.com/1509726/189987642-709ff8b1-168b-40fb-9fb3-b80a5d7698d2.png)

![Screen Shot 2022-09-13 at 2 00 07 PM](https://user-images.githubusercontent.com/1509726/189987644-738c4a98-34a7-4216-adfc-96e61d5b43ab.png)

Your theme:

![Screen Shot 2022-09-13 at 2 00 36 PM](https://user-images.githubusercontent.com/1509726/189987700-97285cdd-bd18-4408-8b6d-5cd67c33538d.png)

I can't seem to replicate the issue. Do you have this project in a public visible repo I could review by chance? Perhaps I can catch something you've missed?
![Screen Shot 2022-09-13 at 2 00 40 PM](https://user-images.githubusercontent.com/1509726/189987703-ce4abffa-19bd-4b71-a7cc-52ad7cd87bfa.png)

**Comment by endigo9740** [comment]
Off the top of my head, the only other thing I'd be curious to see is your Tailwind config. Perhaps share that if the repo is private?

**Comment by figuerom16** [comment]
Project is really barebones.  I'll get it setup in a repo, but here is the config for now.
tailwind.config.cjs
```
const config = {
  content: ["./node_modules/@brainandbones/skeleton/**/*.{html,js,svelte,ts}"],

  theme: {
    extend: {},
  },

  plugins: [require("@brainandbones/skeleton/tailwind.cjs")],
};

module.exports = config;
```

**Comment by endigo9740** [comment]
Ok thanks for sharing. Yeah that looks to be correct. let me know when the repo is ready and I'll pull down and see if I can replicate on my end. But everything I've seen so far looks to be setup correctly.

**Comment by figuerom16** [comment]
Sorry this took me a little bit.  I wanted to do my due diligence and try it again from scratch and reread the documentation.  I hope it's something silly I missed and not a bug.
https://github.com/figuerom16/SkeletonTest

**Comment by endigo9740** [comment]
Thanks! I'm about to step away from my computer for a bit, but I'll look this over tonight and respond asap with my findings. I'm sure we can get it figured out for you!

**Comment by endigo9740** [comment]
@figuerom16 Sorry for the delay, it's been a busy day!

I just pulled down and figured out the issue thought. It's really two small things in your Tailwind config. Here's the full change:

```js
const config = {
  darkMode: 'class',
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    "./node_modules/@brainandbones/skeleton/**/*.{html,js,svelte,ts}"
  ],
  theme: {
    extend: {},
  },
  plugins: [require("@brainandbones/skeleton/tailwind.cjs")],
};

module.exports = config;
```

First, you may want to go ahead an follow Tailwind's recommendation for handling Dark Mode. See the instructions here:
https://tailwindcss.com/docs/dark-mode

We've already got some improvements in place for the documentation in the next release which should make this setting recommendation more obviously. So that's 100% on us! On other note on this, if you're not using the Light Switch component you can manually toggle light/dark mode by applying this class to your `app.html` file:

```
<html ... class="dark">
```

No class = light mode, dark class = dark mode.

The second issue is something I'll try to make more clear in our docs. It looks like you replaced what was present in the `context` setting, but what you needed to do was extend it with the line we provide. By doing so all color stuff seems to be working as expected.

Here's the result with the changes and manually toggling light/dark mode:

![Screen Shot 2022-09-13 at 10 05 43 PM](https://user-images.githubusercontent.com/1509726/190049267-a0297d1c-e25a-4bbc-8017-552506ae8ed3.png)

![Screen Shot 2022-09-13 at 10 05 55 PM](https://user-images.githubusercontent.com/1509726/190049268-00fe1ded-500f-497d-9737-a90946113e88.png)

**Comment by endigo9740** [comment]
One final note. It may help to go ahead and use our stylesheet add-ons. These are just a set of canned styles that will take care of stuff like background color, text color, typography, etc for you. You can still override whatever you wish in your own project's app.postcss (global stylesheet)

https://skeleton.brainandbonesllc.com/guides/styling

Here's the result with this and a few small CSS style tweaks to your page and logo:

![Screen Shot 2022-09-13 at 10 10 34 PM](https://user-images.githubusercontent.com/1509726/190049992-5b504c95-3280-43dd-b32f-8c04f80ce190.png)

![Screen Shot 2022-09-13 at 10 10 44 PM](https://user-images.githubusercontent.com/1509726/190049997-6f7921a2-6300-4746-90df-5d10b3c763f1.png)

Here's the changes:

layout.svelte
```ts
// Theme
  import "../theme.postcss";
  // Skeleton Add-On Stylesheets
  import "@brainandbones/skeleton/styles/tailwind.css";
  import "@brainandbones/skeleton/styles/core.css";
  import "@brainandbones/skeleton/styles/typography.css";
  import "@brainandbones/skeleton/styles/forms.css";
  // Global Stylesheets
  import "../app.postcss";
  import { AppShell, AppBar, Button } from "@brainandbones/skeleton";
```

On your logo I added the following:

```
class="invert dark:invert-0"
```

Finally I dropped everything in your global stylesheet and replace it with:

```css
html,
body {
  @apply h-screen overflow-hidden;
}
```

Hopefully this helps though :)

**Comment by figuerom16** [comment]
Thank you so much for taking the time to go over this!  It works perfectly and is super sleek with the lightswitch and different components I've been trying in the body.  I almost feel like a real frontend person.  (I'm from way in the back.)

You definitely caught me on not knowing Tailwind very well yet; I'm coming from Bulma.io if that says anything.  I did also miss the additive part for tailwind.config.cjs.  The styling guide I flatly glossed way over since I thought it was more of a suggestion than an important piece, not realizing that heavy lifting can be done there by your stylesheets (again not knowing Tailwind well hampered me again).

For people who have squirrels for brains like me I'd like to suggest having some example boiler plate files to use for reference at the end of the guide with the comments in them you have made here.  Guides help me understand, but functional files at the end make me double back into the guide on what I missed and pluck at the files to see what happens.  Destructive learning process.

Sorry, for taking your time.  I'll check the installation links more thoroughly and do better with Github Issues in terms of Version listing, Detailing, Things Attempted, Reproduction, and readily available Repo.

SvelteKit and and your team's project, Skeleton, is allowing someone like me who is not well versed in the frontend, especially css, make beautiful and reactive websites while I get to slink back into the DB and API layer.

I look forward to both of your 1.0 releases.

**Comment by endigo9740** [comment]
Well shoot, those are some kind words! I'm thrilled that our humble little project can help you at all. And much respect to the folks in the "back". I very much appreciate and admire what you do as well.

To be fair I'm still learning Tailwind as well. I really only started using when my partner and I began work on Skeleton ~6 months ago. I'm still learning new tricks and techniques every day. But there's absolutely some room for improvement in our docs. Every time someone like yourself runs into an issue, that makes us aware of some gaps to fill in. Which then makes the process easier for the next guy, so thanks for your small bit of suffering :)

With that in mind I'll spend some time double checking these sections of the docs soon, especially in regards to the light/dark theme settings and Tailwind config. Like I mentioned, I made some updates today that should get us most of the way there. But I'll use your feedback to refine more.

This is all part of the joy of using a pre-release library on-top of a pre-release framework (SvelteKit). There's going to be growing pains until we both hit v1.0!

Again, glad to help. If you experience any other issues don't hesitate to reach out. Likewise I'm on our Discord most of my waking hours, along with a handful of other great contributors. If I can't answer your question in a timely manner then perhaps one of them can jump in an assist.

Thanks again for taking a chance with us though! It's much appreciated! And do be on the lookout for the next update. It includes a but of new polish and new components, but will come with some breaking changes. I hate to do it, but it's a necessary evil that will make things less painful long term! If you're curious you can take a peek here:

https://github.com/Brain-Bones/skeleton/issues/194
