### ISSUE TITLE
Toast with promise

### ISSUE THREAD

**Issue by ak4zh** [Brain-Bones/skeleton#224]
I really like the overall appearance of https://svelte-french-toast.com/
They also have these promise feature:

```js
toast.promise(
    saveSettings(settings),
    {
       loading: 'Saving...',
       success: 'Settings saved!',
       error: 'Could not save.',
    }
);
```

Expectations:
1) Add a similar promise feature
2) Stack toasts one after another horizontally, currently skeleton just throws all toast at same place on top of each other. Click short toast in the demo multiple times you won’t realise new toasts are appearing as they are just stacked on bottom of existing toast.

**Comment by endigo9740** [comment]
Would you mind migrating this comment over to this ticket please:
https://github.com/Brain-Bones/skeleton/issues/198

I can look at modifying the functionality while I'm at it.

Thanks!
