### ISSUE TITLE
Tight version of Buttons and Radio Groups

### ISSUE THREAD

**Issue by jamesnewportbeach** [Brain-Bones/skeleton#226]
Can we get a tight version of the buttons and radio groups? Something less than p-5!!!! - ideally i'd like "text-xs p-2" - I don't see a way to do this currently

**Comment by endigo9740** [comment]
Hey James, we have a button update slated here: https://github.com/Brain-Bones/skeleton/issues/216

Per buttons, would you migrate this comment over to that ticket? It'll help if all information is in one place.

Per radio groups, these have undergone a refactor and redesign. Here's they they'll look like in the next release:

![Screen Shot 2022-09-14 at 4 53 33 PM](https://user-images.githubusercontent.com/1509726/190269715-db2eabc5-ea3f-42c0-a3ba-8e8890cfa1e5.png)

I'm aiming to normalize the size of input-like elements so everything is the same height when laid out horizontally. Something like this:

![Screen Shot 2022-09-14 at 4 51 41 PM](https://user-images.githubusercontent.com/1509726/190269453-b07d517e-8fdb-47bb-91f0-5eb0d191bda6.png)

However, if you still feel keen to adjust the sizing values I can see about adding this. Probably useful for power users anyways, right? :)

**Comment by endigo9740** [comment]
Here's what the radio groups look like in action. We've added better hover states for mouse user:

![radio-groups-anim](https://user-images.githubusercontent.com/1509726/190270342-148395e0-eae0-4fea-9038-0304619eec16.gif)

**Comment by endigo9740** [comment]
@jamesnewportbeach FYI I created a new discussion thread and video update related to these pending updates. See it here: https://github.com/Brain-Bones/skeleton/discussions/231

Feel free to follow the instruction provided if you wish to provide additional feedback on these upcoming changes. For now I'm going to close this ticket. Don't be afraid to pop into the ticket mentioned and continue this conversation though!

Thank you for your continued feedback sir!

**Comment by endigo9740** [comment]
@jamesnewportbeach I wanted to give you a heads up we've nearly complete the update for migrating away from Button components and instead favoring native button/anchor elements, but with Tailwind-like utility classes.

You had requested more control over button sizes, so here's a sneak peak at the defaults. But given these are controlled purely with CSS, you can define any sizing you wish!

![Screen Shot 2022-09-17 at 5 21 58 PM](https://user-images.githubusercontent.com/1509726/190878215-784b44cd-5dcc-48fa-bf01-7d9baf6347c7.png)
