### ISSUE TITLE
Search box minor issues

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#248]
Can't restore full menu when clearing search term with X in search box.
Might make sense to make the box sticky as it will never show via normal navigation (top navbar) unless the user scrolls up in the LHS nav section.  Would also be handy to have it present even when you are browsing in Utilities.

**Comment by endigo9740** [comment]
@niktek FYI I've pushed a small update fix the X button clearing now restoring the menu. I was using the `on:keyup` event, when I should have been using `on:input`. This portion now works as expected.

Making it sticky is a great suggestion, but would require more structural and design changes than I feel comfortable with this late. We'll keep this ticket open to handle this in the next release.

**Comment by endigo9740** [comment]
@niktek a new PR has been filed that adds the sticky search at the top. The AppBar auto-scroll has also been adjusted per the new offset requirements. Please test it out and give a thumbs up. I'll then merge asap.

![Screen Shot 2022-09-26 at 4 07 32 PM](https://user-images.githubusercontent.com/1509726/192380715-6d994d75-22a7-4627-bbfe-4de0b321efc1.png)
