### ISSUE TITLE
Allow selecting range in RangeSlider

### ISSUE THREAD

**Issue by ak4zh** [Brain-Bones/skeleton#261]
Currently, RangeSlider is just a Slider, it does not allow selecting a range.
- Allow selecting range by providing multiple thumbs

![image](https://user-images.githubusercontent.com/26350053/191611699-91b2a546-47e4-4893-bf2a-75fcedf8f7a4.png)

Can be down by adding a low and high prop, or a values array.
Reference: https://github.com/simeydotme/svelte-range-slider-pips#slider-props

**Comment by endigo9740** [comment]
(this is a note for myself)

Needs review: consider dropping component for datalist + action? Keep things as close to native a possible.

**Comment by endigo9740** [comment]
@ak4zh A few things to cover here. First off, let's be clear at what our component actually is - in short, it's wrapper and extended version of the native input:range element:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

We've adopted the name from this. Our version simply provides a pass through for for the built in input functionality, as well as adding on automatic generation of datalist "ticks".

What you're requesting is a custom, non-native component. For reference, see their example page:
https://simeydotme.github.io/svelte-range-slider-pips/

Here's a screenshot of the markup showing their use of divs and spans:
![Screen Shot 2022-09-26 at 4 13 28 PM](https://user-images.githubusercontent.com/1509726/192382146-58471baf-3505-4804-babc-145578fcfbe4.png)

I was going to immediately voice my concerns with a11y for this, but their own example did this for me. See this recording:

![range-slider-issue](https://user-images.githubusercontent.com/1509726/192383338-fd439ecc-73a5-4288-b51d-f421aab7b437.gif)

When trying to inspect the markup, it bugged out and the knob became attached to my mouse position. It continues to follow my mouse around at all times. That's a big problem! Who knows how many possible other edge cases like this exist too. This is why we tend to favor and rely on native elements. They are battle tested, performant, and reliable. With all required a11y built in.

Ideally the native input eventually gets support for min/max values like you've requested. However, in the meantime I'm not sure we can do better than the package you linked. It has lots of options. If you do use it though, just be mindful of the bugs and a11y concerns I raised!

**Comment by endigo9740** [comment]
Just to add one more note - I'd welcome a PR if you want to try your hand at creating a version of this. I just don't think this is something we will make a priority right now though. But thanks for the suggestion!

**Comment by ak4zh** [comment]
I did a bit of research and found a accessible solution someone built, it may not get implemented in this project but adding it here so if someone stumble upon this issue they know of some accessible options they can use:

Original comment: https://stackoverflow.com/a/70561454
SimpleRangeSlider: https://maxshuty.github.io/accessible-web-components/
