### ISSUE TITLE
New Component: File Picker Dropzone

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#268]
References:
https://mantine.dev/others/dropzone/

![Screen Shot 2022-09-26 at 5 04 07 PM](https://user-images.githubusercontent.com/1509726/192388885-7c475ac1-11b0-4072-9e0e-84b2f1dc090b.png)

This will work almost identical to the File Button component:

- https://github.com/Brain-Bones/skeleton/issues/201#issuecomment-1254449966

The only difference is this doesn't include button UI, but rather keeps the input, but styles it to look like the visible droppable region shown above. Native browsers allow for drag and drop on input:file natively. Nothing special needed!

Please follow our contribution guidelines when implementing any new component!
https://skeleton.brainandbonesllc.com/docs/contributions

**Comment by endigo9740** [comment]
@salisshuaibu11 Let me know if you would be interested in this one. Funny enough it's almost identical to the functionality of the File Button. Instead of creating a visible button, you style the input itself to look like the screenshot above. The browser will handle the drag and drop feature natively.

No worries if you want to change it up and work on something else though!

**Comment by salisshuaibu11** [comment]
@endigo9740 I have an intention to work on it already, yeah assign to me.

**Comment by endigo9740** [comment]
Awesome, I've assigned this to you. There's a few ways to handle the input, you might research and see what most folks are doing.

But another idea would be, rather than styling the input itself, you just place it overlapping your styled content, like so:

![image](https://user-images.githubusercontent.com/1509726/192398702-b7785b51-61c5-4cb9-acfc-aa840a602589.png)

Then make sure the overlapping input is set to `visibility:hidden`, which will make it transparent, but still present on the page. Tailwind provides this via the `invisible` class:
https://tailwindcss.com/docs/visibility

That way the input takes precedence, and accepts the files dragged in, but you're free to style the content area and text as you wish behind this.

**Comment by endigo9740** [comment]
Unfortunately Salisu won't be able to continue forward on this one. Any other takers?

**Comment by endigo9740** [comment]
FYI I've decided to take this one. Should be ready soon.

**Comment by endigo9740** [comment]
This component is now available and ready to test on its own branch. See the available PR.

![Screen Shot 2022-09-30 at 3 46 11 PM](https://user-images.githubusercontent.com/1509726/193353677-2f0e6d88-6d7e-4e7b-9dd4-210a1f855268.png)
