### ISSUE TITLE
[Help] Is there any simple way to set roundness of all components to none?

### ISSUE THREAD

**Issue by RadioRambo** [Brain-Bones/skeleton#271]
I want all my components to look rectangular with zero roundness like carbon components. 
Is there any method to achieve those results?

**Comment by endigo9740** [comment]
Not a completely effortless way, but I've been brainstorming some ways to handle this. It may tie into our upcoming theme updates. What I'd actually like to do is make the default square across the board, then allow for a quick manner to override and set that to the desired roundness at a global level. That way everything is consistent. While still being able to override per component if you wish.

For now, your best way to go about this is as follows:

For Tailwind Elements, just apply a global css style for the element:

```css
.card { @apply rounded-none; }
```

For components, it's a similar process, though the class is less obvious. You'll want to either inspect the rendered element in the DOM or look at the component source code here on Github. Each has a "named" class that works kind of like an ID, but is for targeting CSS like this. So for Radio Group that would be:

```css
.radio-group, .radio-item { @apply rounded-none; }
```

> NOTE: you may need to set `!` to make the styles important, like `!rounded-none`. Tailwind classes don't always cascade as you might expect!

Keep an eye out for the next release though. Our newest release just went live last night, and we've been keeping a schedule of release about every 2 weeks.

**Comment by endigo9740** [comment]
FYI I tested the radio group change locally and `!` was not needed.
