### ISSUE TITLE
Theme Generator Randomize Button doesn't change color names

### ISSUE THREAD

**Issue by luke-hagar-sp** [Brain-Bones/skeleton#294]
![Kapture 2022-09-27 at 09 39 42](https://user-images.githubusercontent.com/98849695/192557335-1b2a608e-83ae-4db3-8719-51a2ac1b0b47.gif)

**Comment by endigo9740** [comment]
@luke-hagar-sp Bugfix has been implemented and merged into dev. Code could stand for a bit of a refactor, but this should get us by for now.
