### ISSUE TITLE
Contributor Guide Improvements

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#300]
This section has grown too large and unwieldy. It needs to be reorganized into something people will actually read and use. We should research how others handle this - [Mantine ](https://mantine.dev/pages/contributing/) does a great job in this respect, as usual!

Suggestions:

- Reduce the word count
- Keep only the most important info, drop what's not needed
- Split into multiple sections (pages?), for example:
    - First time contributors
    - Standard contributor info
    - Code style guides
    - Etc
- If we can't find a good way to introduce into the sidebar consider tabs/accordion sections on one page
- Other ideas welcome!

Per first time contributors, I've found two useful links:
- https://opensource.guide/how-to-contribute/
- https://github.com/firstcontributions/first-contributions

Keep it short and summarize the process (fork, branch, update, commit, PR, review, merge)

**Comment by ryceg** [comment]
I'll take this one!

**Comment by endigo9740** [comment]
FYI I went ahead and knocked this out:

![Screen Shot 2022-10-04 at 12 17 28 PM](https://user-images.githubusercontent.com/1509726/193902533-4e8161eb-2cbc-4168-b38d-5a7fd5d39450.png)
