### ISSUE TITLE
Global design token system

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#301]
Found a great video that formalizes the ideas I've had for handling global style settings within Skeleton

- https://vimeo.com/showcase/9653752/video/724689965
- https://user-images.githubusercontent.com/1509726/192694275-a13e2c28-271d-4623-a639-a4a0532b741b.png

We're already doing some of this with our theme color system, however we can go much further. We can use CSS properties as part of our themes files (theme-X.css) to handle the default param-like values for lots of different types of styles, including the following:

- [x] background / hover / active
- [x] text colors
- [x] font families
- [x] border radii
- [x] border: colors / thickness

We'll leave these to be handled by the end user for nowl

- [x] spacing
- [x] padding

**Comment by endigo9740** [comment]
Here's the first draft. By appending a few extra theme properties you can alter the theme in pretty dramatic fashion:

```css
/* --- THEME --- */
--theme-font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
/* Font Color */
--theme-font-color-base: var(--color-surface-900);
--theme-font-color-dark: var(--color-surface-50);
/* Border Radius */
--theme-radius-base: 0px;
--theme-radius-container: 0px;
```

These would be append to the bottom of each theme file. Here's what the results look like customizing the settings a bit. Not the buttons change from slightly rounded, to not rounded, to fully rounded. Likewise the font differs between themes.

![theme-tokens](https://user-images.githubusercontent.com/1509726/194933432-daf8b2cf-e42a-45bf-912c-98a09bc8d53a.gif)

**Comment by endigo9740** [comment]
Background surface tokens will utilize the following structure:

![Uploading image.png…]()

**Comment by endigo9740** [comment]
I've completed my primary pass applying the new design tokens throughout the app, stylesheets, and components.

I've also started work on updating the theme generator to support the new CSS custom properties, which are utilized by the new design tokens. A bit more to be done, but I expect this to be completed sometime tomorrow.

Once this is finished all that's left will be to update the existing preset themes to include the new CSS properties. They will be tailored to make each theme somewhat unique.

![live-preview](https://user-images.githubusercontent.com/1509726/195216214-6a431b3b-1e78-44e2-9ec4-9c7fcada33eb.gif)

**Comment by endigo9740** [comment]
The theme generator has undergone a minor refactor, with a lot of the code and store split up to make it easier to manage. Additionally the UI has been updated and settings (on the right) now persist via a local storage store:

![Screen Shot 2022-10-12 at 1 55 33 PM](https://user-images.githubusercontent.com/1509726/195425337-515ae79f-1ce9-4e8f-8c76-9265d0569649.png)

**Comment by endigo9740** [comment]
All preset themes have been updated, including custom fonts for headings and body text. This feature is now ready for testing!

![Screen Shot 2022-10-12 at 3 48 49 PM](https://user-images.githubusercontent.com/1509726/195444902-216a7656-cc80-450e-af15-29feb1f842f5.png)

**Comment by endigo9740** [comment]
Reopening this to keep it available for QA testing.

**Comment by niktek** [comment]
Probably subjective - but the pagination buttons staying white feels like they should hew closer to the theme colours:

![image](https://user-images.githubusercontent.com/52020637/195666967-90851a57-da00-47f8-aa54-b1f0af872beb.png)

**Comment by niktek** [comment]
Same deal with Range Sliders:
![image](https://user-images.githubusercontent.com/52020637/195667421-2ef43f8a-d13d-4718-ba57-9c5a62320a3e.png)

**Comment by endigo9740** [comment]
@niktek 

Per Paginator/Stepper - believe it or not those are type colors! Here's the class for the generic `.btn-filled`, which they use:

```css
.btn-filled {
	@apply bg-surface-900 dark:bg-surface-50 text-surface-50 dark:text-surface-900;
}
```

I opted for these as they seem like the most neutral for these buttons. There's a `button` property that allows you to overwrite with a different variant, such as `.btn-filled-primary` if you prefer.

Per the theme generator - I've seen that bug too. I plan to address it soon though by changing the condition by which we're applying the background gradient for the default/skeleton theme. That'll come as part of my upcoming design changes. It's annoying though for sure!

**Comment by endigo9740** [comment]
@niktek Per range sliders, test this in Chrome or Firefox. Safari has an unique design for those we cannot adjust.

**Comment by niktek** [comment]
So, I know that my monitor is shit compared to any of the retina displays etc.  But I've noticed that a few of the light themes (Rocket in this case) the disabled state of a button can be quite light.  Don't have a solution, just wanted to raise it in case there is some solution out there.

![image](https://user-images.githubusercontent.com/52020637/195672968-5accf62d-9dd7-4dc2-97af-639880990fc2.png)

**Comment by endigo9740** [comment]
@ryceg I've noticed the new Type updates have started introducing an error on the theme generator component template. It's odd because I don't recall seeing this on when I tested the PR separately

![Screen Shot 2022-10-13 at 1 50 03 PM](https://user-images.githubusercontent.com/1509726/195681808-57d45646-8c86-4de1-9b93-4f9a9d01f001.png)

Looking at this, the use of `number` doesn't seem right:

```ts
export type SemanticNames = typeof semanticNames[number];
export const semanticNames = ['primary', 'accent', 'warning', 'ternary', 'surface'] as const;
```

Changing this appears to fix (most) of the issues in the template, but then we get this error:
![Screen Shot 2022-10-13 at 1 53 40 PM](https://user-images.githubusercontent.com/1509726/195682100-42417a4d-3b45-4f6a-a41a-e7b7e8137002.png)

I've love your help debugging please.

**Comment by endigo9740** [comment]
@niktek @ryceg I've pushed a bugfix for the Hex colors not updating when changed. I'll address the other items later, but I needed that in a working state for my on-going design efforts.

**Comment by endigo9740** [comment]
@ryceg I mentioned it on Discord, but pinging here for redundancy. I think when the TS errors in the theme generator are sorted we can this one complete. If we can resolve this by then I'll aim mark the ticket complete on Monday (my time).

**Comment by endigo9740** [comment]
Marking this completed and ready for release.
