### ISSUE TITLE
Project setup guides for SvelteKit/Vite

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#305]
Check the page linked below, note the three tabs available:

https://skeleton.brainandbonesllc.com/docs/scaffold

Currently we have a guide for Astro, but need something similar for SvelteKit and Vite. We don't need anything fancy, this is just further guidance for folks once they've completed the "Get Started" steps. Ideally we would go through the process of adding a simple component, such as a Slide Toggle.

Volunteers welcome!

**Comment by cananda** [comment]
I set up Skeleton on the latest sveltekit and largely the current docs were good enough and a guide would have been more helpful though. 

For Steppers (https://skeleton.brainandbonesllc.com/components/steppers), I had to change 
import type { Writable } from "svelte/store";
to
import { writable, type Writable } from 'svelte/store';

**Comment by endigo9740** [comment]
A new draft PR has been submitted including updates to the newly dubbed "Framework Guides" section. This includes a new page pointing towards each guide subpage.

![Screen Shot 2022-10-07 at 5 05 27 PM](https://user-images.githubusercontent.com/1509726/194669330-663c79a2-e7af-492d-9387-1c9e1a0ec2c6.png)

Additionally the first draft of the SvelteKit guide has been complete. Though it's a rough draft and will need to be flushed out a bit.

![Screen Shot 2022-10-07 at 5 05 33 PM](https://user-images.githubusercontent.com/1509726/194669309-117e5511-d358-418c-a5df-b7633a4e6999.png)

Vite will be next, followed by some minor updates to the Astro guide.

**Comment by endigo9740** [comment]
The SvelteKit guide has been flushed out and a Vite guide added. This should now be ready for review and testing.

![Screen Shot 2022-10-08 at 1 35 03 PM](https://user-images.githubusercontent.com/1509726/194722567-94814a85-378f-4949-a29f-9c9638f57cd2.png)
