### ISSUE TITLE
Disallow explicit any typing to prevent further typing regressions

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#307]
The ESLint flag can be toggled to disallow explicit `any` typings. 

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md

The only times when explicit any is preferable is when you are converting to TypeScript piece by piece, or when you are dealing with external APIs. Typescript can infer a great deal about data structures. Enforcing this rule will help avoid the need for chore PRs that touch many files, and help keep the components testable.

**Comment by endigo9740** [comment]
We recently moved to a more strict type enforcement (I think a SvelteKit update enabled this for us) and it did take some effort to update. But I do think it's better overall. More strict rules are nice. But there are times where `any` can be useful.

Similar to the other requests, I think this is worth some review and thought.

**Comment by ryceg** [comment]
There are no instances where `any` would be better than `unknown`, which explicitly tells the developer that they are dealing with an unknown object type. This does not enforce explicit typing across the board- merely disallowing typing to `any` explicitly, which is an antipattern. It's a great practice to enforce so that you can't just fob off the typings to later. For typings that you aren't sure of, or don't care about (tableheadings being a good example) you can still leave 'em blank.

As the library grows larger and develops more sophisticated actions and functions, this will become more relevant. It's best to nip it in the bud early to ensure that it's maintainable further down the track. It will be annoying to begin with, but in my personal experience working on a project that enforced zero typescript errors via husky, it made me a much better developer by forcing me to think about the data structure, and research what events/apis I was actually using.

**Comment by endigo9740** [comment]
Right, I understand the technical benefit. If this was a propriety and closed source project I would be all about it. But keep in mind we're working with contributors of all skill levels. I'd rather be able to accept contributions that need typing adjusted or improved versus someone hitting a hard wall and bouncing.

I don't think a zero-tolerance policy will benefit a project of this size this early on. We need all the help we can get at the moment. Instead, perhaps reviewers (myself currently) could do a better job of encouraging and enforcing stricter typing on submissions.

Here's an example of this from today in fact. Sarenor submitted a PR, their first, and it was lacking some key typing, so I submitted an update resolving this. In other instances I might leave a comment and expect the end user to update accordingly.

https://github.com/Brain-Bones/skeleton/pull/304/commits/accf0aa808c34b6f101fba51a990802e9bef67cc

I do agree the project is due for improvements to make more use of typing, but I'm not sure we're in a place where this is such a hard requirement it's worth burning bridges with new contributors.

**Comment by endigo9740** [comment]
FYI I created a post on the Discord contributor channel and pinged a few folks to share their opinion here.

**Comment by ryceg** [comment]
Oh, I should've been more specific- Important to note that this doesn't outright stop commits (unless you set up a git hook to disallow commits/pulls with ESLint errors), but just throws an error, same as if you were to use a method that didn't exist. So contributors would still be able to include that sort of incorrect typing, it's just it would come up as an error.

**Comment by endigo9740** [comment]
Right, but when they receive those errors who are they going to reach out to? :) Right now I'm devoting about a quarter of my working hours to support issues. I'd really appreciate if that went down rather than up.

**Comment by endigo9740** [comment]
After weighing this one for a few days I'd prefer to leave the configuration as is. We can revisit in the future though. I know you don't like `any` Rhys, but honestly the"harm" it produces compared to the number of support issues this might cause isn't justified at the moment. We want a low barrier of entry for contributors.
