### ISSUE TITLE
Create an issue template to streamline UX

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#310]
Using the new yaml format, users can be prompted to provide all the relevant information needed to triage the issue, as well as tag it with appropriate tags. These can be separated into distinct types; the information needed for a documentation typo is different to that of a runtime big, or a feature request. The config file can also be used to direct users to the Discord server if they need support.

**Comment by endigo9740** [comment]
Including a link to a PR with these proposed change on a PR that was not accepted:
https://github.com/Brain-Bones/skeleton/pull/303/files

I think this is a good idea and we should implement this, I'd just like to have a hand in the text for the template(s). Ensure we're prompting for the appropriate information.

**Comment by ryceg** [comment]
Of course! You know what information is most useful for bug reports / feature requests / etc. If you want to specify a list of what inputs you'd like, and the verbiage, I can knock it together.

**Comment by endigo9740** [comment]
@ryceg Just to confirm, this is what the Svelte project is using, correct? Looks like the same categories they use, is that right?

List of options:
https://github.com/sveltejs/svelte/issues/new/choose

Bug report:
https://github.com/sveltejs/svelte/issues/new?assignees=&labels=triage%3A+bug&template=bug_report.yml

A few questions:

1. Are there set categories or can we fully customize these? Say if we need a temporary category or something.
2. The YAML format allows us to completely customize the form fields, correct?
3. If there's official documentation you can link me that would probably answer anything else

FYI I'm still relatively new to GitHub issues. Use them for repos for years, but a lot more PM management in Trello/Jira.

**Comment by ryceg** [comment]
Yes, Svelte uses it.

1. Easy to do!
2. Yes; at the moment you have `input`, `textarea` (longer input), `checkboxes`, and `dropdown` menus, which cover freeform, booleans, and constrained record entries. File input is supported by default.

# Documentation:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
