### ISSUE TITLE
Add documentation for the `unstyled` class

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#313]
Removing styling is possible via adding the `unstyled` class, and this is currently an undocumented feature.

**Comment by endigo9740** [comment]
Note we can also prune some of these old component exceptions while we're at it:
https://github.com/Brain-Bones/skeleton/blob/master/src/lib/styles/typography.css#L30

**Comment by endigo9740** [comment]
I made a few changes here:

- Documented the `.unstyled` class
- Cleaned up the anchor "not" exception list
- Mirrored the `.unstyled` exception to the other Typography elements
- Dropped the typography Taildind plugin which has tripped up a couple people

![Screen Shot 2022-09-30 at 11 19 45 AM](https://user-images.githubusercontent.com/1509726/193313978-b2f6c3e9-cfb8-48c7-a131-a3423c216a2d.png)

![Screen Shot 2022-09-30 at 11 19 53 AM](https://user-images.githubusercontent.com/1509726/193313981-0eafdd50-149a-424e-aacf-e0d2e94513b5.png)
