### ISSUE TITLE
Add Skeleton to Hacktober

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#318]
https://hacktoberfest.com/

I've found Hacktoberfest to be a great way to attract new contributors to projects in the past. Plus, free tshirt!

**Comment by endigo9740** [comment]
It's been suggested already, but honestly it's a matter of finding the time to review what needs to be done.

**Comment by endigo9740** [comment]
I've bookmarked this for review later tonight. I'll make the call and make an announcement on the Discord and Discussions sections if I opt to move forward with this.
