### ISSUE TITLE
I set up Skeleton on the latest sveltekit and largely the current docs were good enough and a guide would have been more helpful though.

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#333]
I set up Skeleton on the latest sveltekit and largely the current docs were good enough and a guide would have been more helpful though. 

For Steppers (https://skeleton.brainandbonesllc.com/components/steppers), I had to change 
`import type { Writable } from "svelte/store";`
to
`import { writable, type Writable } from 'svelte/store';`

_Originally posted by @cananda in https://github.com/Brain-Bones/skeleton/issues/305#issuecomment-1269872100_

**Comment by endigo9740** [comment]
@canada your comment was off topic in the thread you posted it in, so I've moved it here. Thanks for reporting, we'll get this patched up soon!

**Comment by endigo9740** [comment]
@cananda your comment was off topic in the thread you posted it in, so I've moved it here. Thanks for reporting, we'll get this patched up soon!

**Comment by cananda** [comment]
@endigo9740 My apologies, the original issue was about creating a guide for SvelteKit - "Project setup guides for SvelteKit/Vite" and I thought it was relevant there.  Thank you for updating it

**Comment by endigo9740** [comment]
No apology needed, it's part of my job to help keep things organized! Note this has been corrected and will be a part of the next release!

https://github.com/Brain-Bones/skeleton/commit/bbbbfaeb82efad0d3e746e21a39fca99a05a6a60

Thanks for the heads up!
