### ISSUE TITLE
Add href property to GradientHeading for `a` tags

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#353]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Currently, the `GradientHeading` component does not pass through an `href`, which means that it is not usable as a `<a>` element. Ideally, if the `tag` property is specified to be `<a>`, it would also mark the `href` as required.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
I'll go a step further and say we might be keen to use `$$restProps` here. It has some gotchas to be mindful of, but would automatically allow for `target` and potentially may work with the new SvelteKit link option attributes:
https://kit.svelte.dev/docs/link-options

**Comment by endigo9740** [comment]
@ryceg thinking about this a bit, why wouldn't we just wrap the Gradient Heading in an anchor tag for this? That keeps the component a semantic heading tag, but still allows it to be a link. Is there a use case this doesn't cover?

**Comment by ryceg** [comment]
Yeah, I think you're right, as that's what I did for a fix. looking back at it I don't see any use case where we would have to add in this functionality.
