### ISSUE TITLE
Update project dependencies (Svelte/Kit, Tailwind)

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#354]
## Svelte

https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md

Some of these changes may be directly relevant to our in-progress a11y updates. Likewise the updates to `<svelte:element>` may be useful, for expanding dynamic examples within our docs.

## Tailwind:

https://github.com/tailwindlabs/tailwindcss/discussions/9574

This is not live at the time of posting this, but should go live sometime this week.

**Comment by endigo9740** [comment]
FYI I'm waiting on the Tailwind v3.2 release to drop. This should be this week per their communications. Then I'll update all relevant dependencies.

**Comment by niktek** [comment]
Just a heads up that there is also an issue with `target="_blank"` links that have no `rel="noreferrer` - there is a bit of background that I was able to find here:
https://mathiasbynens.github.io/rel-noopener/
https://dev.to/ben/the-targetblank-vulnerability-by-example
https://perishablepress.com/fix-blank-target-vulnerability/ (links to the above two).

Seems like it's a very old bug that's close to being a non-issue in the wild, but those warnings are annoying....

We could do a find and replace on all instances of those strings.
There is also an actions approach from here https://twitter.com/puruvjdev/status/1461065166863273984 but it will only work on components and there may be some issues with SSR pages.

**Comment by endigo9740** [comment]
Tailwind v3.2 includes this new plugin. Super excited about this feature when browser support is more wide spread!
https://github.com/tailwindlabs/tailwindcss-container-queries

**Comment by endigo9740** [comment]
https://tomaszs2.medium.com/svelte-3-52-0-improves-dev-experience-45f8c460bb96

**Comment by LukeHagar** [comment]
😉
