### ISSUE TITLE
Table doesn't fill width if empty content

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#360]
### Current Behavior

![image](https://user-images.githubusercontent.com/52020637/195505811-e8bc55f1-8840-4455-aa80-22087468c9bd.png)

### Anything else?

It also collapses data across the row for an empty cell as you can see for the props that don't yet have a description.

**Comment by endigo9740** [comment]
@niktek Probably best to fold this under this ticket as a request. There's a slew of things the tables don't do...yet.

https://github.com/Brain-Bones/skeleton/issues/217
