### ISSUE TITLE
Theme generator handling of changed hex values

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#363]
### Current Behavior

Updating hex value doesn't update theme colours till the user toggles to Tailwind and back to Hex.  (Confirmed separately from Rhys who originally found it)

### Steps To Reproduce

1: Change over to hex mode
2: Change a Hex value
3: observe it not changing
4: change back to tailwind
5: change back to hex, watch it update with new colours

**Comment by endigo9740** [comment]
Fixed per:
https://github.com/Brain-Bones/skeleton/commit/ce78b354d702bf358948ea1c2d64f20c17e6604e

Nik confirmed this has been resolved in Discord.
