### ISSUE TITLE
Excessive strings showing on packaging Skeleton

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#382]
### Current Behavior

`pnpm package` is showing a lot of `=============== MODIFIED String ==============` messages

This doesn't seem to be affecting the resultant package.

**Comment by endigo9740** [comment]
Unfortunately I'm not able to reproduce with NPM. Perhaps this is limited to PNPM?

![Screen Shot 2022-10-16 at 12 47 15 PM](https://user-images.githubusercontent.com/1509726/196050229-532bb1d9-8a37-4c1c-b1e3-7508fd13cb0b.png)

**Comment by endigo9740** [comment]
Unfortunately I'm not able to reproduce with NPM. Perhaps this is limited to PNPM?

![Screen Shot 2022-10-16 at 12 48 14 PM](https://user-images.githubusercontent.com/1509726/196050276-811865ae-e6bf-400f-a867-54de604131de.png)

**Comment by endigo9740** [comment]
Given your one of the only PNPM members I've assigned this to you. If you find a fix let me know or send a PR please sir!

**Comment by niktek** [comment]
And now it's not happening again.
