### ISSUE TITLE
Dropzone should support required attribute

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#387]
### Current Behavior

Let's make use of `$$restProps` to allow for `required` and any other arbitrary input attributes. The Slide Toggle provides a good reference for how to set this up. Note how we prune `$$restProps.class` to ensure arbitrary classes are still handled on the parent. We don't want those getting copied to the hidden input as well.

### Steps To Reproduce

n/a

### Anything else?

Reported by user `fnf` on Discord in the support channel.

**Comment by endigo9740** [comment]
Note: let's verify the File Button component follows the same pattern.

**Comment by endigo9740** [comment]
@leranjun I've managed to update this and the File Button components to use `$$restProps` which means they will pass any valid input attribute directly to the hidden input embedded within the component. I've also update the documentation for both these, the range slider, and slide toggle to indicate the use of `$restProps` as well.

Thanks for the heads up on this! Expect this update to roll out with the new release coming tomorrow!

**Comment by leranjun** [comment]
Thanks a lot! Looking forward to it!
