### ISSUE TITLE
Ctrl + K to bring up search palette 

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#397]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Similar to [Tailwind's ](https://tailwindcss.com/) search palette, it'd be handy to be able to Ctrl + K (which appears to be sort of a standard search shortcut, with MDN also conforming to this) to the search bar. Would be happy to implement the feature.

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://tailwindcss.com/

https://developer.mozilla.org/en-US/

**Comment by endigo9740** [comment]
We would probably want to get auto-suggest/auto-complete setup alongside this.
https://github.com/Brain-Bones/skeleton/issues/377

**Comment by endigo9740** [comment]
See my updated notes on #377. We'll need to build our own auto-complete component to assist with this. Furthermore it might be ideal to wait until #197 is complete, which may introduce a simpler means for creating custom Dialog templates.

**Comment by endigo9740** [comment]
@ryceg I went ahead and added the keyboard shortcut for this though. It'll just focus in place. We can update the search later when the above changes are ready.

https://github.com/Brain-Bones/skeleton/commit/d80f0227340e6ccb9f42460f2ad5f45c53b6223d
