### ISSUE TITLE
Drawer should trap focus

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#398]
### Current Behavior

Currently, if you bring up the Drawer component, tabbing will still be focused on the main page. 

### Steps To Reproduce

1. Activate a drawer with focusable elements inside
2. Press tab
3. Note that it has not focused on the Drawer element.

**Comment by endigo9740** [comment]
Adding a note for myself: we should also look at giving the Drawer it's own dedicated store, similar to Dialogs/Toasts. Currently users have to roll their own, which requires extra effort.

**Comment by endigo9740** [comment]
Note, a new Trap Focus action was added as part of #197. When merged we can immediately apply it here to knock this out.
