### ISSUE TITLE
Consider renaming "ternary" color to "tertiary"

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#410]
### Current Behavior

This is more semantic an accurate, though a bit harder to spell IMO.

### Steps To Reproduce

n/a

### Anything else?

https://www.merriam-webster.com/dictionary/tertiary

**Comment by ak4zh** [comment]
May be just use `secondary`

Much better:
- Primary
- Secondary
- Accent
- Warning
- Surface

**Comment by endigo9740** [comment]
`Tertiary` is the proper semantic term per the dictionary link in the first post:

> "of third rank, importance, or value"

Here's the updated descriptions in the docs:

![Screen Shot 2022-10-27 at 2 18 18 PM](https://user-images.githubusercontent.com/1509726/198379722-91a179ed-f917-4f2d-a084-a61196ae1c72.png)
