### ISSUE TITLE
Investigate vite error

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#411]
### Current Behavior

On first build of the project without a .svelte-kit folder being present, vite warns in a very brief flyby:
![image](https://user-images.githubusercontent.com/52020637/197079802-b08361c7-275d-4507-8cbe-1f0d6a84e556.png)

Just need to check that our tsconfig.json matches what a new svelte kit project sets up

**Comment by endigo9740** [comment]
@niktek We might want to compare our tsconfig.config against one generated in a fresh SvelteKit project. It's probably not been updated regularly, which means it can be dated back to like February. We shouldn't just drop drop and replace though, as there's some alias info and such that will need to carry over

Maybe we can recruit @ryceg to help as well, given he knows TS better an myself.

**Comment by niktek** [comment]
Same as a new svelte kit project - but that message had been bugging me for ages and I had wanted to know what it was :P
