### ISSUE TITLE
Placeholder animation doesn't seem to animate

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#415]
### Current Behavior

http://localhost:5173/elements/placeholders

I may be too tired or the animation too subtle to see on my monitor, but it doesn't seem to animate anymore.

**Comment by endigo9740** [comment]
You must be tired, as you linked to localhost lol. But it's animating fine for me!

https://www.skeleton.dev/elements/placeholders

![Kapture 2022-10-21 at 10 32 54](https://user-images.githubusercontent.com/1509726/197233646-69a88ea1-8179-4cf1-97b7-cb2fb1272da0.gif)
