### ISSUE TITLE
GradientHeading is imported in +layout, but should be imported in +page

### ISSUE THREAD

**Issue by freedumb2001** [Brain-Bones/skeleton#419]
### Link to the Page

https://www.skeleton.dev/guides/frameworks/sveltekit

### Describe the Issue

GradientHeading is imported in +layout, but should be imported in +page.

https://github.com/Brain-Bones/skeleton/pull/418

### Are you able to create a Pull Request with the fix?

Yes

**Comment by endigo9740** [comment]
This was resolved in the PR, so closing this out.
