### ISSUE TITLE
Limit Paginator's upper bound when exceeding size

### ISSUE THREAD

**Issue by Moosieus** [Brain-Bones/skeleton#426]
### Current Behavior

Presently Paginator's "upper limit" can exceed its `size` prop:
![image](https://user-images.githubusercontent.com/22460600/197683488-b8e8d495-612b-414c-b850-6fa9eb69037b.png)

Instead if the "upper limit" exceeds `size`, it should just render that instead:
![image](https://user-images.githubusercontent.com/22460600/197683392-cf0a4e00-ae00-49a3-b60b-b30dd2571057.png)

### Steps To Reproduce

A quick emulation of the issue can be reproduced as follows:
```svelte
<script>
    import { Paginator } from '@brainandbones/skeleton';
</script>

<Paginator
    offset={1}
    limit={100}
    size={103}
    amounts={[100]}
></Paginator>
```

### Anything else?

_Nope!_

**Comment by leranjun** [comment]
https://github.com/Brain-Bones/skeleton/blob/2940623445457d1338b7450878ddf50a43e9634f/src/lib/components/Paginator/Paginator.svelte#L52-L54

Could be just `Math.min(offset * limit + limit, size)`?

**Comment by leranjun** [comment]
@endigo9740 @Moosieus can we close this? :)

**Comment by endigo9740** [comment]
Yeah, Nik usually uses the "closes" syntax for his PRs. I'll do that now!
