### ISSUE TITLE
SvelteKit guide isn't responsive

### ISSUE THREAD

**Issue by bato3** [Brain-Bones/skeleton#430]
### Link to the Page

https://www.skeleton.dev/guides/frameworks/sveltekit

### Describe the Issue

Building a website should start with the mobile view, and the one in the example sucks...

I suggest change
```xml
<AppShell slotSidebarLeft="bg-surface-500/5 w-56 p-4">
```
to 
```xml
<AppShell slotSidebarLeft="bg-surface-500/5">
```
and maybe add `Drawer` example... (or quick links to docs code)

![image](https://user-images.githubusercontent.com/11570/198027474-597ea195-fa4c-4be3-9b0d-f64bd8ac9726.png)

### Are you able to create a Pull Request with the fix?

No

**Comment by endigo9740** [comment]
@bato3 After thinking it over and reviewing with a couple contributors we all agree this it out of scope for the current guides. If you need assistance with this let me know and I'd be happy to give you some pointers, either here on GitHub or on our Discord #support channel. 

Additionally, if you sent a PR I would have a hard time saying no. Only requirement would be that the instruction is tailored for all three framework guides!

Thanks for the suggestion though!
