### ISSUE TITLE
svelte-add script

### ISSUE THREAD

**Issue by bato3** [Brain-Bones/skeleton#431]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I can't understand installation procedure in Doc. I'm found [skel](https://github.com/Brain-Bones/skeleton/blob/dev/scripts/skel) script, but I can't find a procedure to run it. (Probably I'm so lazy ;-) )

I'm see, that [tailwind adder](https://github.com/svelte-add/tailwindcss/tree/4c0f7323faeea7c529b37056c370a1947bbf3c77#%EF%B8%8F-options) has option to add daisyui.
But I don't think that's the correct approach. Making your adder will allow you to link to the repository that will be under your management.

### What type of pull request would this be?

Other

**Comment by endigo9740** [comment]
Unfortunately Skel is not ended for end users, it's just for internal testing if we need to quickly spin up an instance. @niktek is the author, so if you want specific instruction he can assist you.

I would recommend taking a peek at this ticket: https://github.com/Brain-Bones/skeleton/issues/296

The groundwork is being laid for an automated scaffolding tool for Skeleton, but we probably won't prioritize this until Skeleton is closer to a full v1.0 launch. Right now things are in flux, would means it would take a lot of effort to keep it in sync.

For now I'm going to close this issue. Feel free to add any comments or suggestions for features in the ticket linked above.
