### ISSUE TITLE
Error favicon.ico not found

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#432]
### Current Behavior

![Screen Shot 2022-10-26 at 11 14 03 AM](https://user-images.githubusercontent.com/1509726/198079510-28aaf658-ee11-490d-a8f0-debe0e12c4de.png)

### Steps To Reproduce

Happens when you start the local dev server.

### Anything else?

We should probably create a new/fresh SvelteKit project to see how they handle this by default. Right now we have our favicon declared as:

```html
<link rel="icon" href="%sveltekit.assets%/favicon.png" />
```

But at some point it seems they decided to include the `.ico` variation as well.

**Comment by niktek** [comment]
No reference to an ico file in a new bare Svelte Kit project:

`<link rel="icon" href="%sveltekit.assets%/favicon.png" />`

**Comment by endigo9740** [comment]
Yeah, I have no idea why this started yelling at it. It's only occasionally too. May monitor if it occurs after the dependency bump today or just go ahead and throw a `.ico` in there just in case. I'll need to update the `.png` version with the new design updates incoming anyway.

**Comment by endigo9740** [comment]
I haven't been seeing this pop up today, so I'm going to say the dependency update has fixed it. I'll close for now.
