### ISSUE TITLE
replaceAll warning 

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#433]
### Current Behavior

replaceAll is being used in sveldMapper and is causing a TS warning about upgrading the target output in tsconfig.

Either re-write to not use replaceAll or see what beasts lurk in upgrading the target output

**Comment by endigo9740** [comment]
I've committed a small change to dev branch to fix this:
https://github.com/Brain-Bones/skeleton/commit/b1ae68fdca812472c59a2915e82f3567cfb2c568

If you don't see the change immediately hit `command + shift + P` and type "restart typescript" to see an option to restart the typescript server. This resolved it for me.
