### ISSUE TITLE
Disable non-Skeleton colors appearing in the Intellisense

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#440]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

So, this might be a bad idea, and would likely be something that you'd want to be hidden behind a config flag, but it might be a nice ux improvement to disable the default Tailwind colors in the intellisense, so that only the Skeleton semantic colors show up. 

### What type of pull request would this be?

Enhancement

**Comment by niktek** [comment]
If we could promote the Skeleton ones higher, that would be an ideal solution. I can see times where I would be using more native tailwind colours than Skeleton colours depending on what I was working on.

**Comment by endigo9740** [comment]
Gonna go ahead and nix this one. After thinking it over I think it's important to keep the default colors. If we truly wanted to remove them we could have overwrote theme colors in the Tailwind config. However, we purposely used the "extend" option.
