### ISSUE TITLE
Reenable support for Dialogs with component content?

### ISSUE THREAD

**Issue by evhan** [Brain-Bones/skeleton#446]
### Current Behavior

Hi there! Thanks in advance for Skeleton, lovely project.

Up until the latest release, the Dialog utility let you pass in another component via `component.element` and `props`, which is super useful. But, it looks like that was commented out in [this commit](https://github.com/Brain-Bones/skeleton/commit/a9c706a24793a8ba88ce87463e4ee6497c6fd5db#diff-3d2ffec7fa97e75f1513ba883989d40ca6ad0e465a8a87769d6b7a82186739dfL119-R129) from a week ago, so it's no longer working. I'm talking about this use case:

```javascript
dialogStore.trigger({
  title: 'Hello',
  body: 'Some body text',
  component: {
    element: SomeOtherComponent
  }
})
```

I'm just wondering if there's a reason this was killed, or if it could be resurrected? I've reenabled that code in a local copy and things still seem to work just fine in the new version, for what it's worth, but maybe there's a different way we should be doing this now?

Thanks again!

### Steps To Reproduce

1. Using the Dialog utility
2. Trigger a new dialog with `component.element = SomeOtherComponent` (and optionally `component.props` containing some element properties).
3. Nothing happens

**Comment by endigo9740** [comment]
Hey @evhan thanks for the kind words! And sorry about that, it seems I missed that change in the release notes. Unfortunately I can't recall the specifics for why it was disable. I seem to recall there being an issue I couldn't debug before release.

That said, I want to draw your attention to this ticket:
- https://github.com/Brain-Bones/skeleton/issues/197

Between this, toasts, and data tables, those are the "big three" that I have on my docket to refactor and overhaul soon. Per Dialogs one of my main goals is to make the components not just a tacked on feature, but a core part of how these work. Allowing you to define your own custom interchangeable templates to to fill the full contents of the dialog window. This will draw inspiration from how Angular Material handles these, if you're familiar.

Unfortunately things just keep cropping up and delaying these! But I will make a consorted effort to make these updates the priority not this upcoming release, but the the release after that. My goal tomorrow (my time) will be to go through and sort bug tickets like this one, so keep an eye on this ticket. I'll revert the change that removed this, or at least give you a good reason for why it's disable!

Sorry again and thanks for your patience!

**Comment by endigo9740** [comment]
And if you have any other ideas or suggestions please drop them in that ticket linked above. That's what it's for!

**Comment by endigo9740** [comment]
@evhan I've managed to restore this feature in the library. After reviewing I was reminded why it was disabled - the component we were using for our example (Cards) was removed and replaced with the Tailwind Elements. This would have broke the example. This should have been updated, not removed, so that's my bad!

I've now restored this feature and updated the documentation to demonstrate it again. This may still change with the proposed refactor in the future. But this should get you by for now. Expect this to be part of a the next release.

**Comment by evhan** [comment]
Amazing, thanks so much @endigo9740!

I've just installed the library from that latest commit and can confirm things are working again in my project. So, that's all good, and I really appreciate the quick response.

I'll have a read through the linked issues and see if I can add anything useful there too. Cheers!
