### ISSUE TITLE
Button loses all Skeleton styling if disabled value changed when class property set

### ISSUE THREAD

**Issue by neiled** [Brain-Bones/skeleton#45]
Hi,

Maybe I'm doing something really wrong but if I have something simple like:
```
<Button
  disabled={!enabled}
  type="submit"
  variant="filled-primary"
  class="inline-flex ml-3">
    Save
</Button>
```

And I change the enabled variable value from true to false, I lose all the Skeleton styling and only the 'class' values are used for styling.

If can't reproduce let me know a decent website I can post an example to and happily will.

**Comment by endigo9740** [comment]
Thanks Neil, I'll take a look asap!

**Comment by endigo9740** [comment]
I've been able to replicate the issue on my end. Seems it's a side effect of our use of Svelte's `$$restProps`. This is a catch-all for miscellaneous properties so we don't have to specify every possible anchor or button attribute (ex: target, type, etc).

We experienced a similar issue that would occur on initialization of the component, but patched this in the last release. Unfortunately this fix doesn't extend to when a component prop updates, resulting in the unstyled component you're seeing.

I'm aware of about 5 components this bug may be affecting. I think it may be advisable for us to drop `$$restProps` and find another means to handle miscellaneous attributes. That or take the whitelist approach and build up over time.

Working on a couple other things this week, but I'll try to swing back to this as soon as I can. Thanks for making me aware of this issue!

**Comment by neiled** [comment]
Absolutely, good luck with it, looks great, I love sveltekit and tailwindcss so this project will be a godsend for internal tools etc. Thanks for all the work so far!

**Comment by endigo9740** [comment]
Thanks for the kind words!

Making a note here for a potential fix:
- If we add `class` as a prop for any component using `restProps` then this should resolve out issue.
- This will mean we have two types of props: always declared and potentially declared
- This will supersede the need for the `delete` fix from last patch

**Comment by endigo9740** [comment]
FYI Neil, I've pushed a potential fix for this issue to my in-progress QA branch: https://github.com/Brain-Bones/skeleton/commit/d19ad6781a4ddd68a5a41bb014801322f620f704

I'm going to let Thomas, our resident QA expert, give this a once over before I consider this complete. If I was a betting man I'd expect this to see this in a release later this week though. Thanks for your patiences in the meantime!

**Comment by thomasbjespersen** [comment]
@endigo9740 - Looking into this now.

**Comment by thomasbjespersen** [comment]
Confirmed this will be fixed by the merge of d19ad67...

**Comment by endigo9740** [comment]
Merged: https://github.com/Brain-Bones/skeleton/pull/50

**Comment by endigo9740** [comment]
@neiled FYI this is now released:
https://github.com/Brain-Bones/skeleton/releases/tag/0.30.4

**Comment by endigo9740** [comment]
Sorry for the double post, but updating to 0.30.5 or later this issue should now be resolved for you:
https://github.com/Brain-Bones/skeleton/releases/tag/0.30.4
https://github.com/Brain-Bones/skeleton/releases/tag/0.30.5

**Comment by neiled** [comment]
Thanks that's great will give it a whirl!
