### ISSUE TITLE
SEO Component

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#450]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

A component that provides an exhaustive list of the SEO attributes that you're all too likely to forget- the benefit being primarily that you would be able to use intellisense to prompt yourself to not forget, like a checklist of sorts

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

I swear I remember seeing this somewhere. I'll remember where

**Comment by niktek** [comment]
Added to the #355 issue, but there is the https://github.com/oekazuma/svelte-meta-tags MetaTag component already kicking

**Comment by endigo9740** [comment]
Given these overlap in these two issues I'm going to close this one. Let's continue anything SEO related over in #355
