### ISSUE TITLE
Improve test cases for components using restProps

### ISSUE THREAD

**Issue by thomasbjespersen** [Brain-Bones/skeleton#46]
If we add class as a prop for any component then it won't be included restProps. See https://github.com/Brain-Bones/skeleton/issues/45 for more details.

This should be a test that is applied to all applicable components.

**Comment by endigo9740** [comment]
Currently the only components using restProp are the following:

* Button
* LogoCloud > Logo
* Range Slider
* Slide Toggle

These are the only tests that will need to be updated for now, but we should be mindful of following this pattern if we extend the use of restProp to additional components in the future.
