### ISSUE TITLE
Calculation of last record number for last page should show total records

### ISSUE THREAD

**Issue by suryapratap** [Brain-Bones/skeleton#464]
https://github.com/Brain-Bones/skeleton/blob/7e0ca54338021bf7e4da596dce03b1caa08aeb49/src/lib/components/Paginator/Paginator.svelte#L53

this should be corrected to 
```jsx
   {offset * limit + 1} to { Math.min(offset * limit + limit, size)} of <strong>{size}</strong>
```

**Comment by endigo9740** [comment]
Thanks @suryapratap, hey @niktek do you mind jumping on this if you get a chance?

**Comment by niktek** [comment]
It's already fixed in `dev` branch https://github.com/Brain-Bones/skeleton/pull/447
