### ISSUE TITLE
Missing Dialog and Snackbar type exports

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#47]
The following need to included as exports in `/src/lib/index.js`

```js
// Dialog Types
import { type DialogAlert, type DialogConfirm, type DialogPrompt } from '@brainandbones/skeleton';
```
```js
// Toast Types
import { type Toast } from '@brainandbones/skeleton';
```
This does not match the expectations provided in the current documentation instructions.

**Comment by endigo9740** [comment]
I created regarding this issue on the Svelte Discord. I figured I'd shared here as well, just in case:
https://discord.com/channels/457912077277855764/1004975444459790356

Long story short, I need to know the best means to export custom Typescript interfaces as part of the package. Trying to do this in index.js, similar to a component, does not work. I figure there's just a slightly different syntax that's needed, similar to `import type {}`...but of course the other way around.

I'll research and test a bit more soon, however, I welcome any support in the meantime!

**Comment by niktek** [comment]
https://github.com/Brain-Bones/skeleton/pull/72

The types have to be exported in a .ts file, doing this in `src/lib/index.d.ts` will block the autogenerated component exports that are created by `svelte-kit package`, so this is a quick little workaround to get custom types added to the root `@brainandbones/skeleton` namespace

**Comment by endigo9740** [comment]
This is great, looks like it'll do exactly what is needed, but I'll need to request a couple other small changes. I'll reject the PR and post comments there to make it obvious. Check there shortly.

**Comment by endigo9740** [comment]
Between Nik and myself, we appear to have a fix for this. See my latest comment here:
https://github.com/Brain-Bones/skeleton/pull/73

Long story short, we just need to rename `index.js` -> `index.ts` and then we can drop our Type exports right in!
