### ISSUE TITLE
DataTableService exports

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#478]
### Current Behavior

There is currently two exports from DataTableService that are used internally of DataTable.svelte (sortAsc and sortDesc), then there is a mapTableSource that is used in the doc page for data-tables.

On the docs page there is also a CodeBlock that shows an import of `import { mapTableSource } from '@brainandbones/skeleton/components/Table/DataTableService';` which I'm pretty sure won't work as the alias `@brainandbones/skeleton` points to the `src/index.ts` rather than a directory alias.

What probably needs to happen is that these DataTableService exports need to migrate to the top level src/index.ts file and probably have a bit of a namespace scoping like dtsSortAsc or something like that ?

**Comment by endigo9740** [comment]
@niktek Dupe? https://github.com/Brain-Bones/skeleton/issues/217

Would be easiest if all this info is one place when I finally get to the component again.

**Comment by niktek** [comment]
I'll drop a note over there - just needed to get this fix in as part of the #479 PR

**Comment by endigo9740** [comment]
The PR looks to be closed, so I've linked to this on the Data Table ticket. Closing this for now. Let's keep data table notes in that ticket. I plan to address those updates as part of this current dev cycle!
