### ISSUE TITLE
Allow default Tailwind's darkMode : media strategy

### ISSUE THREAD

**Issue by rbaprado** [Brain-Bones/skeleton#482]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I would not like to have a LightSwitch, I would rather have the UI follow the desired system option only, as tthe default Tailwind "media" dark mode strategy.

I tried setting darkMode: media under tailwind.config.cjs but got compilation issues. Am I missing something here?

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
There shouldn't be any part of Skeleton that would cause compilation issues for you. I'd recommend you verify all your settings in your config are set properly. Perhaps share your config here along with the error your received?

I haven't personally used the media option but in theory it should work. If not it seems like something we could support. There just hasn't been a lot of interest until now. I've marked this as a feature request to review though.

**Comment by rbaprado** [comment]
@endigo9740 you are absolutely right, it was something on my side (a node_modules cleanup did the trick).

Sorry for bothering you guys with that, great work by the way!

**Comment by endigo9740** [comment]
Glad you got it sorted! Let us know if if we can help with anything else!
