### ISSUE TITLE
Dark version of the logo

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#497]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Jord on discord is giving a presentation soon and it would be great if we can give him a dark version the logo that will sit well on this page:

![Uploading image.png…]()

**Comment by jordharr** [comment]
Its'a me! If you can send it over i'd appreciate :)

**Comment by endigo9740** [comment]
@niktek @jordharr Here's a quick set I threw together and dropped on Notion. There's .zip files you can download that contain a set of images:

https://walnut-fly-221.notion.site/Skeleton-Presskit-be8b41488d20423aa76a836d44bf5d3e

The `logos.zip` is the one you'll want. Look in the PNG folder for a black variation of the logo icon/text.
