### ISSUE TITLE
Onboarding documentation updates

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#512]
### Link to the Page

https://www.skeleton.dev/guides/install

### Describe the Issue

Guides improvements:

- Overall: Make it more obvious what is being done and why
- Tailwind: show explicit example of complete tailwind.config file
- Styling: provide explicit snippet showing the required CSS import order 
- Stying: make removing the @tailwind directives really obvious
- Themes: move design tokens to Tailwind > Design Tokens, but reference them
- Frameworks: make it clear this is optional

Additionally we should look at adding a new Docs > FAQ section with questions such as:

- Q: Is typescript required? A: no, but recommended
- ...

### Are you able to create a Pull Request with the fix?

Yes

**Comment by endigo9740** [comment]
A PR has been implemented for review:

- PR: https://github.com/Brain-Bones/skeleton/pull/513
- Preview: https://skeleton-mjmpu8f7r-skeleton-ui.vercel.app/

This includes the following improvements.

## General

- Reordered Docs and Guides categories in the sidebar navigation rail
- Tailwind > Design Tokens - the new home for design token information, will flush out soon.
- Improved the "next step" info at the bottom of each Guides section

## Docs

- FAQs: new section w/ several questions implemented (more welcome!)
- Comparisons: minor UI update
- Features: minor UI update

## Guides

- Installation: prereqs added, FAQ linked
- Tailwind: improved instruction, fixed broken Lightswitch link
- Themes: bumped up before Styling, improved Theme Color info, moved Design Tokens
- Styling: refactored the whole page with many styles, but should be more informative
- Frameworks: made obvious this is optional, added "what's next" section to guide progress

**Comment by niktek** [comment]
Lets try making the main Guides step through buttons be primary-filled

**Comment by endigo9740** [comment]
Bug: The `all.css` stylesheet isn't showing in the Styling page code block due to a conditional issue.

**Comment by niktek** [comment]
https://dev.skeleton.dev/guides/install - vite svelte, probably not best to `npm run dev` at this point ?

**Comment by endigo9740** [comment]
All above items have been addressed and pushed.
