### ISSUE TITLE
Tooltips disappearing when cursor touches child component (e.g. icon on a button)

### ISSUE THREAD

**Issue by geoffkendall** [Brain-Bones/skeleton#519]
### Current Behavior

A tooltip on a button appears when the mouse enters it, but disappears as soon as the cursor moves over the icon contained within that button. As far as I can tell this doesn't affect text-only buttons unless the text is part of another child component such as a `<span>` tag. 

### Steps To Reproduce

The following code should replicate the problem:

```
<button class='btn btn-icon ttaMenu' 
  use:tooltip={{ content: 'Text', position: 'left' }}
>
  <span><UserCircle size='30'/></span>
</button>
```

### Anything else?

Thank you! :-)

**Comment by endigo9740** [comment]
@Sarenor mentioned he might can sort this tomorrow. I'll watch for a PR.

Please make sure to include `Fixes #519` in the PR please!
