### ISSUE TITLE
New Utility: CodeBlock

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#52]
The Skeleton documentation has been using the `<CodeBlock>` component internally for a white. I believe it's adequately mature now. Let's go ahead and document this and make available as part of the library.

This will include the following changes:

* Add Utilities > Code Blocks to the Skeleton docs navigation
* Minor updates to the CodeBlock documentation, including instructions for setting up Highlight.js
* Add the CodeBlock component to the package exports in `/lib/index.js`

**Comment by endigo9740** [comment]
@thomasbjespersen This is now ready for QA. Thanks!

**Comment by thomasbjespersen** [comment]
@endigo9740 Any reason why you are not specifying HTML as lang in the usage, and instead using plaintext? 

`<CodeBlock code={'<CodeBlock language="html" code={\`<div>This is meta</div>\`}></CodeBlock>'}></CodeBlock>`

**Comment by endigo9740** [comment]
Seems that got dropped by accident. I'll patch that real quick!

**Comment by endigo9740** [comment]
@thomasbjespersen I see what you mean, Highlight.js wasn't properly highlighting the code snippet because it's the Svelte syntax. They support a ton of languages, but unfortunately Svelte does not appear to be one of them.

https://highlightjs.org/static/demo/

**Comment by thomasbjespersen** [comment]
@endigo9740 But all of our other components docs utilize this. By adding html as the language? 
![Screen Shot 2022-08-05 at 5 07 08 PM](https://user-images.githubusercontent.com/52718757/183222111-f280e19c-f4f1-4a30-a97d-f5225b99fce5.png)

**Comment by thomasbjespersen** [comment]
We are good to merge this branch to master, @endigo9740.
