### ISSUE TITLE
 Main Vertical navigation links not working<title>

### ISSUE THREAD

**Issue by OStirbu** [Brain-Bones/skeleton#524]
### Current Behavior

![Nov-11-2022 20-59-57](https://user-images.githubusercontent.com/25176671/201422556-8b0a3ba0-3080-4aed-a030-fe0ac3700883.gif)

### Steps To Reproduce

https://www.skeleton.dev/guides/install

### Anything else?
Macbook M1. Chrome 
_No response_

**Comment by endigo9740** [comment]
Hey @OStirbu Can you check and see if any console errors are reported. Grab those and shared them here before you follow my next steps please. I want to make sure what the error is before we resolve it.

Once that's done, try these steps:

1. Right click anywhere and open inspect.
2. Select the `Application` tab
3. Choose `Local Storage` from the options on the left
4. Hit the circle/slash icon near the top middle (right the Filter search box).

This will clear all Local Storage values for the site. Then refresh and see if the issue persists. If it does you should be seeing console errors from above. Ensure they've remained.

And sorry about this, we pushed out a fix a week or so ago that resolved this for most people. But for some reason it's still affecting a few users.

**Comment by OStirbu** [comment]
Solved it. Big kudos and keep it up.
