### ISSUE TITLE
Modal click event handling

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#546]
### Current Behavior

1. click down in the content of the modal
2. drag to backdrop 
3. mouseup (imagine a large select of content in the modal that goes out of bounds of the Modal)

The Modal is dismissed.  Feels like the content should capture the click and the modal click event would then correctly handle the down/up event only when the user explicitly clicks on the backdrop

**Comment by endigo9740** [comment]
I've made three small changes to fix this:

- Dropped the `on:click` method on the backdrop
- Added `on:mousedown` and `on:touchstart` to replace it
- Renamed the triggered method `onBackdropInteraction` to be sementic

By using the down/start events only the BEGINNING of the event will trigger this. Drag click/tap and then releasing won't work.
