### ISSUE TITLE
Search Modal can be instantiated multiple times

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#555]
### Current Behavior

It's actually kinda cool :P But if you cmd-k you can bring up search, hit cmd-k again and a new instance overlays.  Hitting escape will cancel the topmost one and re-init the underlying instance.

**Comment by endigo9740** [comment]
Oh boy, I knew we would have some trouble getting this in last minute. Whoops!

**Comment by endigo9740** [comment]
Fixing this alongside: https://github.com/Brain-Bones/skeleton/issues/546
