### ISSUE TITLE
Master branch is 3 commits ahead of dev

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#558]
### Current Behavior

Need to either merge those commits to dev branch or delete them if they were added to dev separately.

**Comment by endigo9740** [comment]
I resolved this, but then the new cherry-pick has put it ahead by 1 again. We'll have to remember to update when we get to the next release. Your PR change should be merged into master though.

![Screen Shot 2022-11-16 at 11 06 18 AM](https://user-images.githubusercontent.com/1509726/202246323-f3522824-4f6b-4ce4-befd-9e2e7f6b0fa1.png)
