### ISSUE TITLE
Change event listener for `SlideToggle`

### ISSUE THREAD

**Issue by dumtux** [Brain-Bones/skeleton#562]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Is it possible to have event listener of SlideToggle like this?

```html
<script lang="ts">
	import { SlideToggle } from '@brainandbones/skeleton';
	let is_checked: boolean = false;

	function onChange() {
		console.log(is_checked);
	}
</script>

<div class="page-container">
	<SlideToggle bind:checked={is_monitoring} on:change={() => {onChange()}}>{is_checked ? 'Activated' : 'Disabled'}</SlideToggle>
</div>
```

How can I get on-change event instead of polling `is_checked` status manually?

**Comment by endigo9740** [comment]
Hey @dumtux I'd recommend checking the source code to see how we forward events for this component. Most events are attached to the hidden checkbox input within the component template:

https://github.com/Brain-Bones/skeleton/blob/dev/src/lib/components/SlideToggle/SlideToggle.svelte#L75

This is also included in the component documentation:

![Screen Shot 2022-11-16 at 12 53 09 PM](https://user-images.githubusercontent.com/1509726/202268104-49fc8d42-6321-4154-98db-769212e618ab.png)

So an `on:change` event handler should work but you'll need to reformat it a bit:

```html
<SlideToggle bind:checked={is_monitoring} on:change={onChange}</SlideToggle>
```

Then your console.log in the function should return the expected value. If for some reason you wish to obtain the state directly from the event, you would modify your `onChange` function like so:

```js
function onChange(event: any) {
    console.log(e.target.value);
}
```

Let me know if this works for you!

**Comment by endigo9740** [comment]
Note, small issue above that I've corrected. It should be `event.target.checked` not value!

**Comment by dumtux** [comment]
Yes, this worked perfectly.
I had to check the documentation in more detail.

**Comment by endigo9740** [comment]
@dumtux No worries, glad it worked. Note we're still in the process of adding and refining events in the docs, so some components may lack desired events. 

We have a ticket to address this in the near future though:
- https://github.com/Brain-Bones/skeleton/issues/389
