### ISSUE TITLE
Folder case change

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#57]
src/lib/button card and divider have lower case folder names, which cause an issue in src/lib/index.js imports and is probably why the @ts-nocheck was applied.  Just need to capitalise the folder names and remove the ts-nocheck.

**Comment by thomasbjespersen** [comment]
Great catch, @niktek. I have been wanting to get this done for a while.

**Comment by endigo9740** [comment]
Thanks Nik. Strangely enough my local instance has the correct casing. I'm guessing I addressed this at some point but Git didn't pick it up. This should now be fixed on on the Master branch. Thanks for bring it to my attention!
