### ISSUE TITLE
Aspect Ratio TW plugin

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#570]
### Current Behavior

No matter what combo I do (pure create-svelte | svelte-add | skeleton-installer), I'm still getting an error, so something is wrong in either the instructions on @tailwindlabs/aspect-ratio, or tailwind proper is no longer respecting the disabling of `corePlugins: { aspectRatio: false }` or it's something in Skeleton.

The best way to get the error with correct pointers to the line numbers is to add aspect-ratio into skeleton itself.

`npm i -D @tailwindcss/aspect-ratio`

And adjust `tailwind.config.js` to:

```
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
	darkMode: 'class',
	content: ['./src/**/*.{html,js,svelte,ts}'],
	corePlugins: {
		aspectRatio: false,
	},
	theme: {
		extend: {
			fontFamily: {
				sans: ['Inter', ...defaultTheme.fontFamily.sans]
			}
		},
		aspectRatio: {
			auto: 'auto',
			square: '1 / 1',
			video: '16 / 9',
			1: '1',
			2: '2',
			3: '3',
			4: '4',
			5: '5',
			6: '6',
			7: '7',
			8: '8',
			9: '9',
			10: '10',
			11: '11',
			12: '12',
			13: '13',
			14: '14',
			15: '15',
			16: '16',
		},
	},
	plugins: [require('@tailwindcss/forms'), require('./src/lib/tailwind/theme.cjs'), require('@tailwindcss/aspect-ratio')]
};
```
This will give an error of:
```CssSyntaxError: [postcss] /Users/nik/code/skeleton/src/lib/styles/elements/buttons.css:49:3: The `aspect-square` class does not exist. If `aspect-square` is a custom class, make sure it is defined within a `@layer` directive.```

But looking in `elements/button.css` you can 100% see that the `.btn-icon` class is nested within an `@layer components` so I'm at a bit of a loss as to where things are wrong.

**Comment by endigo9740** [comment]
After reviewing with @niktek we're going to drop Skeleton support for this plugin:
https://github.com/Brain-Bones/skeleton/issues/571
