### ISSUE TITLE
Skeleton Divider Border Width - Cannot replicate behaviour in docs

### ISSUE THREAD

**Issue by VaughanG** [Brain-Bones/skeleton#582]
### Current Behavior

I followed the Skeleton Guides to getting set up and decided to add a Divider component in +page.svelte.
_https://www.skeleton.dev/components/dividers_ shows the ability to set Border Width at 8 with borderWidth="border-t-8".
This is the code I used:
`<Divider borderWidth="border-t-8" borderStyle="border-solid" borderColor="border-primary-500" />`

Unfortunately this produces a thin line of no more than 2 pixels height.

I have tried Firefox and Edge browsers.

I must be missing something? 

### Steps To Reproduce

Add the Divider component to a page.
Set the Border Width to 8 with border-t-8.
Unlike the Usage tab instructions at https://www.skeleton.dev/components/dividers
the browser seems to limit the border width to approximately 2.

### Anything else?

![divider](https://user-images.githubusercontent.com/37030783/202881208-39a7d788-eb8a-4b69-9bec-8b55e15602db.jpg)
```
<script>
	import { GradientHeading } from '@brainandbones/skeleton';
	import { Divider } from '@brainandbones/skeleton';
</script>

<div class="container mx-auto p-8 space-y-8">
	<GradientHeading tag="h1" direction="bg-gradient-to-r" from="from-primary-500" to="to-accent-500">
		Homepage
	</GradientHeading>
	<br />
	<Divider borderColor="border-primary-500" borderWidth="border-t-8" borderStyle="border-solid" />

	<br />

	<section class="card card-body">
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
	</section>
	<section class="flex space-x-2">
		<a
			class="btn btn-filled-primary"
			href="https://kit.svelte.dev/"
			target="_blank"
			rel="noreferrer">SvelteKit</a
		>
		<a
			class="btn btn-filled-accent"
			href="https://tailwindcss.com/"
			target="_blank"
			rel="noreferrer">Tailwind</a
		>
		<a class="btn btn-filled-tertiary" href="https://github.com/" target="_blank" rel="noreferrer"
			>GitHub</a
		>
	</section>
</div>

```

**Comment by endigo9740** [comment]
@VaughanG This is odd, I tried copying your exact snippet above and this is working fine for me:

![Screen Shot 2022-11-20 at 12 24 19 PM](https://user-images.githubusercontent.com/1509726/202919239-a0016c63-c641-4879-ba62-d72fe51b5d68.png)

Overall your styles seems to be working from your screenshot, but can you verify a couple things for me:

- Can you verify you're using `all.css`. If you're attempting to use stylesheets piecemeal I have som ideas here:
- Can you share your CSS imports in your root layout. Screenshot or code snippet is fine.
- Verify you removed the @tailwind directives from your global stylesheet please. They will include:

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by VaughanG** [comment]
Thanks @endigo9740 - Here is _+layout.svelte_ which shows the import of all.css and theme-seafoam.css and app.post.css
```
<script>
	import '@brainandbones/skeleton/themes/theme-seafoam.css';

	import '@brainandbones/skeleton/styles/all.css';

	import '../app.postcss';

	import { AppShell, AppBar } from '@brainandbones/skeleton';
</script>

<AppShell slotSidebarLeft="bg-surface-500/5 w-56 p-4">
	<!-- Header -->
	<svelte:fragment slot="header">
		<AppBar>
			<svelte:fragment slot="lead">
				<h1>Skeleton</h1>
			</svelte:fragment>
			<svelte:fragment slot="trail">
				<a class="btn btn-sm" href="https://github.com/" target="_blank" rel="noreferrer">GitHub</a>
			</svelte:fragment>
		</AppBar>
	</svelte:fragment>

	<!-- Sidebar -->
	<svelte:fragment slot="sidebarLeft">
		<nav class="list-nav">
			<ul>
				<li><a href="/">Home</a></li>
				<li><a href="/about">About</a></li>
			</ul>
		</nav>
	</svelte:fragment>
	<!-- Page Content Slot -->
	<slot />
</AppShell>

```
Here is app.postcss
```
html,
body {
	@apply h-full overflow-hidden;
}
```

**Comment by endigo9740** [comment]
Thanks for confirming. Yeah everything looks to be fine there. Let me circle back on this one when I have a bit more bandwidth, ok? If you don't posting a repro project I can clone and test quickly though that might be the easiest way to go about this. No rush, just as you can please.

**Comment by VaughanG** [comment]
Thanks again endigo9740 the repo is _https://github.com/VaughanG/svelskeleton_. I understand that you are super busy so no worries about waiting.

**Comment by endigo9740** [comment]
@VaughanG Sorry again for the delay on this. I had a chance to review your project and found the issue. It's a small but critical thing. Not the line I highlighted here:

![Screen Shot 2022-11-21 at 10 37 32 AM](https://user-images.githubusercontent.com/1509726/203110411-a4ddbf01-1f14-4b7c-8a69-250bd26ff0b6.png)

You must keep the existing Tailwind default settings for `content` and append the line we suggest here. These each serve an important purpose:

1. The existing line tells the Tailwind compiler to search for Tailwind classes locally within your project files
2. The line we add via the instructions searches for Tailwind classes within the `node_modules` directory

With without number 1, you were only picking up style changes from the latter, and not the former.

Here's the complete config:

```js
const config = {
	darkMode: 'class',

	content: [
		"./src/**/*.{html,js,svelte,ts}",
		require('path').join(require.resolve('@brainandbones/skeleton'), '../**/*.{html,js,svelte,ts}')
	],

	theme: {
		extend: {}
	},

	plugins: [require('@brainandbones/skeleton/tailwind/theme.cjs')]
};

module.exports = config;
```

Applying this change caused the styling to work immediately as expected.
