### ISSUE TITLE
Tests and lint issues

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#67]
Just a quick heads up:

When running `npm run test`, Avatar, Button and Alert had issues with `@testing-library/dom` not being present - needs to be added to the package.json

`npm run lint` is currently showing issues in 141 files - just want to check what's going on here.

Cheers,
Nik

**Comment by endigo9740** [comment]
Tests were working fine last I checked, but I'll review. And yes, we've been doing a bad job keeping up with linting. Definitely something to be addressed soon. I'd assume most are minor issues.

**Comment by endigo9740** [comment]
FYI we'll keep this ticket in regards to the testing issue indicated above. I've created another ticket here to address linting: https://github.com/Brain-Bones/skeleton/issues/70

**Comment by thomasbjespersen** [comment]
@niktek If you won't mind, could you share more details about the issues you encountered about the tests? Screenshots or copy/paste would be fine.

**Comment by niktek** [comment]
Hey @thomasbjespersen,
Okay, so on a fresh fork, cd'd to the root of the project folder:

`pnpm i`
vitest-svelte-kit 0.0.6 (0.0.7 is available) deprecated
`pnpm dev`
The request url "/Users/nik/code/github/skeleton/.svelte-kit/runtime/client/start.js" is outside of Vite serving allow list.
`pnpm test`
Error: [vite-node] Failed to load @testing-library/dom

There is only @testing-library/svelte in package.json and no @testing-library/dom in the devDependncies so that one is quick to fix.  I imagine vitest-svelte-kit can be removed due to it all being native to Vite now (adding vitest on a new project didn't pull in the vitest-svelte-kit either)?

I need to look into the outside of Vite serving allow list a bit more

**Comment by niktek** [comment]
Looks like they are all resolved with this: https://github.com/Brain-Bones/skeleton/pull/74

**Comment by thomasbjespersen** [comment]
@niktek - Hey Nik! I have been unable to replicate this from my side. Please comment on this ticket if further issues should arise.. We can always reopen if needed.

**Comment by thomasbjespersen** [comment]
This cannot be reproduced under regular circumstances..

**Comment by thomasbjespersen** [comment]
Tests were working fine.. Closed..

**Comment by niktek** [comment]
I'm still able to repro this 

If you look at:
https://github.com/Brain-Bones/skeleton/blob/master/package.json
There is no `@testing-library/dom`, so it is impossible for it to work without doing a manual install of that library. Can you check that you don't have `@testing-library/dom` installed as a global package (`npm list -g`) from multiple projects maybe ?

And - https://www.npmjs.com/package/vitest-svelte-kit it's not meant to be used any more.

If you just delete your node_modules folder and do `npm i` then you will at least see the deprecation warning and removing the package will show the need for the fixes in vitest.config.js

**Comment by endigo9740** [comment]
@thomasbjespersen @niktek Given Nik is the first contributor to pull down the project and run the test suite, I'd like to troubleshoot what's going on. Especially since he's able to reproduce. I'll investigate on my end and respond with my findings asap.

**Comment by endigo9740** [comment]
@niktek FYI I've had a chance to run through and test this again. Steps to reproduce:

1. Pull on my local master branch to ensure it's current
2. Run `npm run test` to run the test runner
3. No errors are present

![Screen Shot 2022-08-13 at 3 14 04 PM](https://user-images.githubusercontent.com/1509726/184509388-7c45018b-00fd-4afe-ab1c-50dfc2d9a6be.png)

Unless you can produce steps to reproduce or other folks can replicate it may be a local issue on your side. If that's the case we will close the ticket. I'll wait until you follow up before I do that though.

**Comment by niktek** [comment]
Okay, this one was bugging me and I needed to get to the bottom of it.

It's because I use pnpm... BUT
https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html

Substitute @testing-library/dom for the debug@1 in the article to understand the issue.  Because it is not listed in skeletons dependencies, even though it directly uses it, it is at the 'mercy' of testing library who can change/remove it.  In this case it is very trivial and small and not likely to have major flow on effects.

Also, npm for some reason is also happy to install the deprecated package without even warning you of such, which will cause an issue at some point.

`pnpm i` on the other hand lets you know that something is up and you should be looking into it. 
![image](https://user-images.githubusercontent.com/52020637/184562821-0d04ec18-85dc-42bd-a147-da115c48ff72.png)

 I also don't like wasting 200mb per project by having exact copies of files in each projects node_modules folder.

So I'm going to propose, properly adding the @testing-library/dom to package.json to resolve the pnpm DX and we can sort out the deprecated testing package in another issue.

That work for you guys ?

**Comment by endigo9740** [comment]
I'm all for this. I think this will tie in well with the Vitest config updates we've been brainstorming, but I'm fine with it happening sooner.
