### ISSUE TITLE
Decouple Skeleton from SvelteKit

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#68]
Expand Skeleton's support and instruction for any framework where Svelte and Tailwind can be used. Including, but not limited to:

* ~[Vite](https://vitejs.dev/)~ - via https://github.com/Brain-Bones/skeleton/issues/83 - works with v0.32.19+
* ~[Astro](https://astro.build/blog/astro-1/)~ - via https://github.com/Brain-Bones/skeleton/issues/93 - works with v0.32.19+
* [Routify](https://www.routify.dev/) - (coming soon)
* Client-side only or Micro-Framewoks:
    * Symphony for PHP - via https://github.com/Brain-Bones/skeleton/issues/85 (need more testing on this)
    * (Django/Flask for Python, ..., others?)
* (welcoming other suggestions here)

**Comment by niktek** [comment]
New svelte project with ts, added Skeleton and just tried doing an import of all the components, these are the ones that error out:

`
  import Alert from './lib/Alert/Alert.svelte';  //referes to $lib/Card
  import Avatar from './lib/Avatar/Avatar.svelte';  //refers to $lib/Filters
  import CodeBlock from './lib/CodeBlock/CodeBlock.svelte' // fails to resolve highlight.js
  import Filter from './lib/Filters/filter' //refers to $lib/Filters/svg/* 
  import LightSwitch from './lib/LightSwitch/LightSwitch.svelte'; // refers to $app/env
  import Menu from './lib/Menu/Menu.svelte'; //refers to $app/stores
  import Dialog from './lib/Notifications/Dialog.svelte'; //refers to $lib/Button
  import Toast from './lib/Notifications/Toast.svelte'; //refers tp $lib/Notifications
  import Paginator from './lib/Paginator/Paginator.svelte'; //refers to $lib/Button
  import Step from './lib/Stepper/Step.svelte'; //refers to $lib/Button
  import ThemeGenCustom from './lib/ThemeGenerator/ThemeGenCustom.svelte'; //refers to palettey
  import ThemeGenTailwind from './lib/ThemeGenerator/ThemeGenTailwind.svelte'; //refers to CodeBlock
`

Main issues are $lib reference doesn't exist in Svelte and then we have the trickier ones where functionality is received from $app/stores and $app/env

**Comment by endigo9740** [comment]
Ok, not too bad. Per Skeleton's documentation Highlight.js is an additional required dependency to use CodeBlocks so that makes sense. Follow the instruction on the doc and that should just leave the other two.

LightSwitch uses the following to determine if the app is loaded in the browser, a lifecycle hook essentially. There may be another way to go about this:
`import { browser } from "$app/env";`

Switching to a Svelte supported lifecycle hook may be enough to resolve that. Something like onMount:
[`import { onMount } from 'svelte';](https://svelte.dev/tutorial/onmount)

That just leaves the menu issue mentioned in the original post. Perhaps we could use an onDestory method to handle closing the menu automatically. Something like:
https://svelte.dev/tutorial/ondestroy

This seems reasonable. May require a bit of testing but I think we can make it happen!

**Comment by JensPfeifle** [comment]
`npm install highlight.js --save-dev` as suggested in the docs didn't fix the HighlightJS issue for me. This is with npm/Vite/Svelte and Skeleton v0.30.7.
![image](https://user-images.githubusercontent.com/23027708/184494374-d8ebb809-f129-43d0-a56a-70f799c3ec97.png)

**Comment by endigo9740** [comment]
Hi Jens, first off sorry for the issue. Unfortunately this is not related to the decoupling process mentioned above. I've created a new ticket for this here: https://github.com/Brain-Bones/skeleton/issues/83

I'll follow up there.

**Comment by endigo9740** [comment]
@JensPfeifle has provided a great PR to help with the first half of this ticket.

https://github.com/Brain-Bones/skeleton/pull/82

This prunes the SvelteKit-specific features from either component per the suggestions above. However, I'll delay the merge until we can also document and provide instructions for how to install and setup Skeleton for other tools like Vite, Astro, etc.

The partial (but probably incomplete) list of those is in the original post above. I welcome anyone's instructions for documenting the process for each of these tools. Post them here and I'll find a means to merge it all together and update the homepage when ready.

**Comment by endigo9740** [comment]
Per FYI: https://github.com/Brain-Bones/skeleton/issues/86

CodeBlock will be disabled from the next release until further notice. We'll revisit a different way to implement this and reintroduce in a future update.

**Comment by endigo9740** [comment]
Documentation for Astro is ready, per: https://github.com/Brain-Bones/skeleton/issues/93

**Comment by endigo9740** [comment]
Per the original post, #83 and #93 have been closed as these changes have been merged from Dev. We still need review and cleanup of the doc changes, but these and the a11y updates were getting a bit too stale on their own branches.

**Comment by bkcsfi** [comment]
Hi,

Sveltekit just changed $app/env to $app/environment, this broke  my app because LightSwitch.svelte version 0.0.1 refers to $app/env

**Comment by endigo9740** [comment]
Yeah, the LightSwitch underwent a fairly large change in 0.32.19 that would correct this. Sorry for the confusion @bkcsfi

**Comment by endigo9740** [comment]
I'm feeling pretty confident about the three primary frameworks we support right now, so I'm going to go ahead and close this issue. If requests come in for Routify or similar we can always generate new tickets in the future.
