### ISSUE TITLE
Highlight.js is a dev dependancy

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#76]
All of the testing I have been doing so far was based on forking and working in the skeleton repo itself, not using it in a brand new project.

When creating a new svelte-kit project as per the getting started guide, as soon as you import a component (e.g. Card), it will complain that it is not able to resolve highlight.js for CodeBlock, which makes sense as in the skeleton repo highlight.js is listed as a dev dependency.  Either docs need to be updated to tell end users to install it `npm I highlight.js`, which does fix the issue, or it is added as a non dev dependancy to Skeleton UI.

**Comment by endigo9740** [comment]
Fixed?
https://github.com/Brain-Bones/skeleton/releases/tag/0.30.7

**Comment by endigo9740** [comment]
Fixed! Wohoo!
