### ISSUE TITLE
Avatars show as square in iOS Safari

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#80]
Reported on Reddit here:
https://www.reddit.com/r/sveltejs/comments/wmnkoi/comment/ik1a8va/?utm_source=share&utm_medium=web2x&context=

I've reproduced the issue in the iOS simulator here. Most likely a missing overflow:hidden style! Note it only occurs for avatars using an image source as shown:

![Screen Shot 2022-08-12 at 2 40 21 PM](https://user-images.githubusercontent.com/1509726/184431378-9d605364-be5c-4502-ac24-d80adbf7fcaf.png)

**Comment by snake-345** [comment]
iOS: 15.6
![image](https://user-images.githubusercontent.com/3379833/184431480-e31a4378-9057-48fe-bb80-ec39331e2ab6.png)

I see that you crop an image with `object-fit: cover;` looks like it doesn't work in mobile safari correctly.

**Comment by endigo9740** [comment]
Perfect, thanks Snake!

**Comment by endigo9740** [comment]
Fixed and merged into `dev` branch.
