### ISSUE TITLE
Upgrading to Svelte Kit 408

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#96]
I did a dry run through and it went really smoothly.  Notes:

Must upgrade to SK version 405 `pnpm i @sveltejs/kit@1.0.0-next.405`
Then `npx svelte-migrate routes` which will transform all the pages under routes/
Unpin 405 in package.json and upgrade to 408

Everything works, even the data tables demo pages.
However, it clearly renames all of the files under routes - so creating a PR for this, even if it was based off the a11y branch is not going to be a nice merge.  This would also be a good time to start looking at release/* branches to merge multiple feature branches into without jeopardising master in case of a hot fix release being needed.

**Comment by endigo9740** [comment]
Ahh it's arrived, eh? Sounds like the migration tool is working well, that's great to hear.

The good news is we don't have to update this moment. We can wait until the a11y and decoupling updates are merged down. Also agreed on the new branches. I'm going to create a ticket to handle this tomorrow.

**Comment by endigo9740** [comment]
FYI: https://github.com/Brain-Bones/skeleton/issues/97

**Comment by endigo9740** [comment]
![Screen Shot 2022-08-16 at 4 51 29 PM](https://user-images.githubusercontent.com/1509726/184991701-aacd2c6b-b7f9-4f09-9b6b-b353c98c4aa7.png)

Noting the change to the global stylesheet is now `app.postcss`. Probably best to address this after the next release given instructions will need to be changed in multiple places per the decoupling doc updates.
