### ISSUE TITLE
Basic SEO for Docs Site

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#99]
Per [Roadmap > Documentation > SEO](https://github.com/Brain-Bones/skeleton/wiki/%F0%9F%9B%A3%EF%B8%8F-The-Skeleton-Roadmap-(proposal))

Make some minor modifications to the HTML `<head>` element to include the following:
https://www.link-assistant.com/news/html-tags-for-seo.html

* Title - more descriptive
* Meta Description
* Meta Keywords
* Meta Theme Color (because why not)
* Open Graph Tags ([reference](https://ogp.me/))
    - Title
    - Description
    - Type
    - (more later)

**Comment by xmlking** [comment]
https://mskocik.github.io/svelecte/
I wish I can style this with tailwind css, that is why I want this component offered in skeleton
